/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_ucmbt_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_UCMBT_DEF_H
#define _MMI_RP_APP_UCMBT_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_UCM_BT_CALLING = 45222 + 1, /* BASE_ID + 1 */
    STR_ID_UCM_BT_REJECT,
    STR_ID_UCM_BT_ANSWER,
    STR_ID_UCM_BT_RETRIEVE,
    STR_ID_UCM_BT_END_CALL,
    STR_ID_UCM_BT_UNMUTE,
    STR_ID_UCM_BT_HAND_HELD,
    STR_ID_UCM_BT_HAND_FREE,
    STR_ID_UCM_BT_ACTIVE,
    STR_ID_UCM_BT_PAIRED_HOLD,
    STR_ID_UCM_BT_CALL_ENDED,
    STR_ID_UCM_BT_PROCESSING,
    STR_ID_UCM_BT_CALL_WILL_BE_ENDED,
    STR_ID_UCM_CONN_BT_FIRST,
    STR_ID_UCM_BT_CONF_CALL,
    STR_ID_UCM_BT_REPLACE,
    STR_ID_UCM_BT_NO_RESPONSE,
    STR_ID_UCM_BT_CALL_FAILED,
    STR_ID_UCM_BT_UNHOLD,
    STR_ID_UCM_BT_STATE_HELD,
    STR_ID_UCM_BT_REJECT_THE_CALL,
    STR_ID_UCM_BT_END_THE_CALL,
    STR_ID_UCM_BT_RECONN_CNF,
    STR_ID_UCM_BT_ACCEPTING,
    STR_ID_UCM_BT_ENDING,
    STR_ID_UCM_BT_SWAPPING,
    STR_ID_UCM_BT_UNHOLDING,
    STR_ID_UCM_BT_REJECTING,
    MMI_RP_APP_UCMBT_STR_MAX
}mmi_rp_app_ucmbt_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_UCM_BT_PRE_MO = 45222 + 1, /* BASE_ID + 1 */
    GRP_ID_UCM_BT_MO,
    GRP_ID_UCM_BT_MT,
    GRP_ID_UCM_BT_INCALL,
    GRP_ID_UCM_BT_CALL_END,
    GRP_ID_UCM_BT_DEV_NOTI,
    GRP_ID_UCM_BT_HW_CNF,
    GRP_ID_UCM_SGL_CONN_CNF,
    SCR_ID_UCM_BT_OUTGOING,
    SCR_ID_UCM_BT_INCOMING,
    SCR_ID_UCM_BT_IN_CALL,
    SCR_ID_UCM_BT_CALL_END,
    SCR_ID_UCM_BT_PROCESSING,
    SCR_ID_UCM_BT_DUMMY,
    SCR_ID_UCM_BT_DIALLING,
    SCR_ID_UCM_END_AND_ACCEPT_CONFIRM,
    SCR_ID_UCM_BT_DTMF_EDITOR,
    SCR_ID_UCM_BT_DEV_NOTIFY,
    SCR_ID_UCM_BT_HW_CNF,
    SCR_ID_UCM_SGL_CONN_CNF,
    MMI_RP_APP_UCMBT_SCR_MAX
}mmi_rp_app_ucmbt_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    UCM_NOTIFY_DURATION_TIMER_BT = 45222 + 1, /* BASE_ID + 1 */
    UCM_TONE_AFTER_VIBRATION_BT,
    UCM_MO_PROCESSING_TIMER_BT,
    UCM_FORCE_REFRESH_TIMER_BT,
    UCM_VOL_BAR_SHOW_TIMER_BT,
    UCM_VOL_STR_SHOW_TIMER_BT,
    UCM_VOL_SET_DELAY_TIMER_BT,
    UCM_FTE_AUTO_LOCK_TIMER_ID_BT,
    MMI_RP_APP_UCMBT_TIMER_MAX
}mmi_rp_app_ucmbt_timer_enum;
/******************** Timer resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_UCM_BT_CALL_END = 45222 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_UCMBT_EVENT_MAX
}mmi_rp_app_ucmbt_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_UCM_BT_OUTGOING = 45222 + 1, /* BASE_ID + 1 */
    IMG_ID_UCM_BT_INCOMING,
    IMG_ID_UCM_BT_IN_CALL,
    IMG_ID_UCM_BT_CALL_STATE_HOLD,
    MMI_RP_APP_UCMBT_IMG_MAX
}mmi_rp_app_ucmbt_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_UCMBT_DEF_H */
