/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_scr_locker_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_SCR_LOCKER_DEF_H
#define _MMI_RP_APP_SCR_LOCKER_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_SLK_TIME_SETTING_MENU = 28290 + 1, /* BASE_ID + 1 */
    MENU_ID_SLK_SETTING_OFF,
    MENU_ID_SLK_SETTING_15_SEC,
    MENU_ID_SLK_SETTING_30_SEC,
    MENU_ID_SLK_SETTING_1_MIN,
    MENU_ID_SLK_SETTING_5_MIN,
    MMI_RP_APP_SCR_LOCKER_MENU_MAX
}mmi_rp_app_scr_locker_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_SLK_UNLOCK = 28290 + 1, /* BASE_ID + 1 */
    STR_ID_SLK_KBD_HELP_MSG,
    STR_ID_SLK_KBD_HELP_MSG2,
    STR_ID_SLK_KBD_UNLOCK_ME_MSG,
    STR_ID_SLK_TIME_SETTING,
    STR_ID_SLK_15_SEC,
    STR_ID_SLK_30_SEC,
    STR_ID_SLK_1_MIN,
    STR_ID_SLK_5_MIN,
    MMI_RP_APP_SCR_LOCKER_STR_MAX
}mmi_rp_app_scr_locker_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_SLK_MAIN = 28290 + 1, /* BASE_ID + 1 */
    SCR_ID_SLK_MAIN,
    GRP_ID_SLK_SETTING,
    GRP_ID_SLK_MAIN_WDEVICE,
    GRP_ID_SLK_MAIN_SCREEN_WDEVICE,
    MMI_RP_APP_SCR_LOCKER_SCR_MAX
}mmi_rp_app_scr_locker_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    KEYPAD_LOCK_TIMER = 28290 + 1, /* BASE_ID + 1 */
    IDLE_APP_AUTO_LOCK_TIMER_ID,
    MMI_RP_APP_SCR_LOCKER_TIMER_MAX
}mmi_rp_app_scr_locker_timer_enum;
/******************** Timer resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_SCR_LOCKER_LOCKED = 28290 + 1, /* BASE_ID + 1 */
    EVT_ID_SCR_LOCKER_UNLOCKED,
    EVT_ID_SLK_OBJ_CLOSE_REQ,
    EVT_ID_SLK_OBJ_CLOSED_IND,
    EVT_ID_SCREEN_LOCK_KEY_PRE_LOCK_EVT_ROUTING,
    MMI_RP_APP_SCR_LOCKER_EVENT_MAX
}mmi_rp_app_scr_locker_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/


/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_SETTING_AUTOKEYPADLOCK = 28290 + 1, /* BASE_ID + 1 */   /*         BYTE */ 
    NVRAM_SETTING_AUTOKEYPADLOCK_TIME,                          /*         BYTE */ 
    MMI_RP_APP_SCR_LOCKER_MMI_CACHE_MAX
} mmi_rp_app_scr_locker_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


#endif /* _MMI_RP_APP_SCR_LOCKER_DEF_H */
