/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_srv_blecm_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#ifndef _MMI_RP_SRV_BLECM_DEF_H
#define _MMI_RP_SRV_BLECM_DEF_H




/******************** Timer resource IDs - begin ********************/
typedef enum
{
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID0 = 18187 + 1, /* BASE_ID + 1 */
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID1,
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID2,
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID3,
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID4,
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID5,
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID6,
    SRV_BLE_UPDATE_CONN_INTERVAL_TIMER_ID7,
    SRV_BLE_SET_ADV_INTERVAL_TIMER_ID,
    MMI_RP_SRV_BLECM_TIMER_MAX
}mmi_rp_srv_blecm_timer_enum;
/******************** Timer resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    SRV_LE_CM_EVENT_CONNECT_REQ = 18187 + 1, /* BASE_ID + 1 */
    SRV_LE_CM_EVENT_CONNECT_CNF,
    SRV_LE_CM_EVENT_DISCONNECT_REQ,
    SRV_LE_CM_EVENT_DISCONNECT_CNF,
    SRV_LE_CM_EVENT_VIS_CNF,
    SRV_LE_CM_EVENT_INQUIRY_IND,
    SRV_LE_CM_EVENT_INQUIRY_COMPLETE,
    SRV_LE_CM_EVENT_SET_VISIBILITY,
    SRV_LE_CM_EVENT_UPDATE_NAME,
    MMI_RP_SRV_BLECM_EVENT_MAX
}mmi_rp_srv_blecm_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/


#endif /* _MMI_RP_SRV_BLECM_DEF_H */
