/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_bt_dialer_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_BT_DIALER_DEF_H
#define _MMI_RP_APP_BT_DIALER_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_BT_DIALER_TITLE = 44383 + 1, /* BASE_ID + 1 */
    STR_ID_BT_SPEAKER_TITLE_MESSAGE,
    MMI_RP_APP_BT_DIALER_STR_MAX
}mmi_rp_app_bt_dialer_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_BT_DIALER = 44383 + 1, /* BASE_ID + 1 */
    GRP_ID_BT_SPEAKER,
    SCR_ID_BT_SPEAKER,
    SCR_ID_BT_SPEAKER_REFRESH_SCREEN,
    MMI_RP_APP_BT_DIALER_SCR_MAX
}mmi_rp_app_bt_dialer_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    BT_AVRCP_CT_CMD_FRAME_TIMEOUT = 44383 + 1, /* BASE_ID + 1 */
    BT_A2DP_SINK_STREAM_START_TIMER,
    BT_SPEAKER_LOADING_SCREEN_TIMER,
    MMI_RP_APP_BT_DIALER_TIMER_MAX
}mmi_rp_app_bt_dialer_timer_enum;
/******************** Timer resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_BT_DIALER_DISCONN_EVENT_ID = 44383 + 1, /* BASE_ID + 1 */
    EVT_ID_DIALER_EVENT_ALL_CALL_END_ID,
    MMI_RP_APP_BT_DIALER_EVENT_MAX
}mmi_rp_app_bt_dialer_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/


/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_BT_SPEAKER = 44383 + 1, /* BASE_ID + 1 */             /*         BYTE */ 
    MMI_RP_APP_BT_DIALER_MMI_CACHE_MAX
} mmi_rp_app_bt_dialer_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_BT_MAIN_SKIN1_PREV = 44383 + 1, /* BASE_ID + 1 */
    IMG_ID_BT_MAIN_SKIN1_NEXT,
    IMG_ID_BT_MAIN_SKIN1_PLAY,
    IMG_ID_BT_MAIN_SKIN1_PAUSE,
    IMG_ID_BT_MAIN_SKIN1_STOP,
    IMG_ID_BT_MAIN_SKIN1_BUTTON,
    IMG_ID_BT_MAIN_SKIN1_HIGHLIGHT_BUTTON,
    MMI_RP_APP_BT_DIALER_IMG_MAX
}mmi_rp_app_bt_dialer_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_BT_DIALER_DEF_H */
