/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_vdoply_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_VDOPLY_DEF_H
#define _MMI_RP_APP_VDOPLY_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_VDOPLY_APP = 45967 + 1, /* BASE_ID + 1 */
    MENU_ID_VDOPLY_FILE_OPTION,
    MENU_ID_VDOPLY_EMPTY_FOLDER_OPTION,
    MENU_ID_VDOPLY_OPTION,
    MENU_ID_VDOPLY_OPTION_STREAMING,
    MENU_ID_VDOPLY_PLAY,
    MENU_ID_VDOPLY_STORAGE,
    MMI_RP_APP_VDOPLY_MENU_MAX
}mmi_rp_app_vdoply_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_VDOPLY_APP_NAME = 45967 + 1, /* BASE_ID + 1 */
    STR_ID_VDOPLY_NOTIFY_STORAGE_NOT_READY,
    MMI_RP_APP_VDOPLY_STR_MAX
}mmi_rp_app_vdoply_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_VDOPLY_START = 45967 + 1, /* BASE_ID + 1 */
    GRP_ID_VDOPLY_APP,
    SCR_ID_VDOPLY_APP,
    GRP_ID_VDOPLY_PLAYER,
    GRP_ID_VDOPLY_STREAMING_URL,
    SCR_ID_VDOPLY_STREAMING_URL,
    SCR_ID_VDOPLY_PREDEFINED_URL,
    SCR_ID_VDOPLY_HISTORY_URL,
    GRP_ID_VDOPLY_HISTORY_OPTION,
    SCR_ID_VDOPLY_HISTORY_OPTION,
    GRP_ID_VDOPLY_URL_EDITOR,
    SCR_ID_VDOPLY_URL_EDITOR,
    SCR_ID_VDOPLY_URL_EDITOR_OPTION,
    GRP_ID_VDOPLY_SINGLE_PLAYER,
    SCR_ID_VDOPLY_PLAYER,
    SCR_ID_VDOPLY_OPTION,
    GRP_ID_VDOPLY_BROWSER,
    GRP_ID_VDOPLY_STORAGE,
    SCR_ID_VDOPLY_STORAGE,
    GRP_ID_VDOPLY_NETWORK_PROFILE,
    SCR_ID_VDOPLY_NETWORK_PROFILE,
    SCR_ID_VDOPLY_NETWORK_PROFILE_OPTION,
    GRP_ID_VDOPLY_NETWORK_PROFILE_EDIT,
    GRP_ID_VDOPLY_NETWORK_PROFILE_EDIT_DA,
    SCR_ID_VDOPLY_NETWORK_PROFILE_EDIT,
    SCR_ID_VDOPLY_NETWORK_PROFILE_RENAME,
    GRP_ID_VDOPLY_SETTINGS,
    GRP_ID_VDOPLY_ADJUST_OPTION,
    SCR_ID_VDOPLY_ADJUST_OPTION,
    GRP_ID_VDOPLY_STREAM_EDITOR,
    SCR_ID_VDOPLY_STREAM_EDITOR,
    SCR_ID_VDOPLY_STREAM_EDITOR_OPTION,
    SCR_ID_VDOPLY_END,
    MMI_RP_APP_VDOPLY_SCR_MAX
}mmi_rp_app_vdoply_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/


/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_VDOPLY_VOLUMN = 45967 + 1, /* BASE_ID + 1 */          /*         BYTE */ 
    NVRAM_VDOPLY_ACTIVE_PROFILE_IDX,                            /*         BYTE */ 
    NVRAM_VDOPLY_PROXY_IP1,                                     /*         BYTE */ 
    NVRAM_VDOPLY_PROXY_IP2,                                     /*         BYTE */ 
    NVRAM_VDOPLY_PROXY_IP3,                                     /*         BYTE */ 
    NVRAM_VDOPLY_PROXY_IP4,                                     /*         BYTE */ 
    NVRAM_VDOPLY_PROXY_ON_OFF,                                  /*         BYTE */ 
    NVRAM_VDOPLY_SNAPSHOT_SEQ_NO,                               /*        SHORT */ 
    NVRAM_VDOPLY_STORAGE,                                       /*        SHORT */ 
    NVRAM_VDOPLY_OPTION_BRIGHTNESS,                             /*        SHORT */ 
    NVRAM_VDOPLY_OPTION_CONTRAST,                               /*        SHORT */ 
    NVRAM_VDOPLY_OPTION_REPEAT,                                 /*        SHORT */ 
    NVRAM_VDOPLY_OPTION_PLAY_MODE,                              /*        SHORT */ 
    NVRAM_VDOPLY_STREAM_SEQ_NO,                                 /*        SHORT */ 
    NVRAM_VDOPLY_PROXY_PORT,                                    /*       DOUBLE */ 
    NVRAM_VDOPLY_HIGHEST_UDP_PORT,                              /*       DOUBLE */ 
    NVRAM_VDOPLY_LOWEST_UDP_PORT,                               /*       DOUBLE */ 
    MMI_RP_APP_VDOPLY_MMI_CACHE_MAX
} mmi_rp_app_vdoply_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_VDOPLY_APP_ICON = 45967 + 1, /* BASE_ID + 1 */
    IMG_ID_VDOPLY_OSD_BUTTON_PLAY,
    IMG_ID_VDOPLY_OSD_BUTTON_PAUSE,
    IMG_ID_VDOPLY_OSD_BUTTON_STOP,
    IMG_ID_VDOPLY_OSD_BUTTON_BACK,
    IMG_ID_VDOPLY_OSD_BUTTON_FORWARD,
    IMG_ID_VDOPLY_OSD_BUTTON_FULLSCREEN,
    IMG_ID_VDOPLY_OSD_BUTTON_VOL_NULL,
    IMG_ID_VDOPLY_OSD_BUTTON_VOL_FULL,
    IMG_ID_VDOPLY_OSD_BUTTON_MUTE,
    IMG_ID_VDOPLY_OSD_BUTTON_MUTE_DOWN,
    IMG_ID_VDOPLY_OSD_BUTTON_UNMUTE,
    IMG_ID_VDOPLY_OSD_BUTTON_UNMUTE_DOWN,
    IMG_ID_VDOPLY_OSD_TIMER_0,
    IMG_ID_VDOPLY_OSD_TIMER_1,
    IMG_ID_VDOPLY_OSD_TIMER_2,
    IMG_ID_VDOPLY_OSD_TIMER_3,
    IMG_ID_VDOPLY_OSD_TIMER_4,
    IMG_ID_VDOPLY_OSD_TIMER_5,
    IMG_ID_VDOPLY_OSD_TIMER_6,
    IMG_ID_VDOPLY_OSD_TIMER_7,
    IMG_ID_VDOPLY_OSD_TIMER_8,
    IMG_ID_VDOPLY_OSD_TIMER_9,
    IMG_ID_VDOPLY_OSD_TIMER_COL,
    IMG_ID_VDOPLY_LSK_OPTION_UP,
    IMG_ID_VDOPLY_LSK_OPTION_DOWN,
    IMG_ID_VDOPLY_RSK_BACK_UP,
    IMG_ID_VDOPLY_RSK_BACK_DOWN,
    IMG_ID_VDOPLY_OSD_HIGHLIGHT,
    IMG_ID_VDOPLY_OSD_PROGRESS_BG,
    IMG_ID_VDOPLY_OSD_PROGRESS_FILL,
    IMG_ID_VDOPLY_OSD_LOADING_BG,
    IMG_ID_VDOPLY_OSD_LOADING_FULL,
    IMG_ID_VDOPLY_OSD_LOADING_EMPTY,
    IMG_ID_VDOPLY_OSD_LOADING_FILL,
    IMG_ID_VDOPLY_OSD_AUD_ONLY_ANIM,
    MMI_RP_APP_VDOPLY_IMG_MAX
}mmi_rp_app_vdoply_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_VDOPLY_DEF_H */
