/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_smsbtunifiedmessage_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_SMSBTUNIFIEDMESSAGE_DEF_H
#define _MMI_RP_APP_SMSBTUNIFIEDMESSAGE_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MAIN_MENU_SMS_BT_MESSAGES_MENUID = 48307 + 1, /* BASE_ID + 1 */
    MENU_ID_SMS_UM_WRITE_MSG,
    MENU_ID_SMS_UM_INBOX,
    MENU_ID_SMS_UM_DRAFT,
    MENU_ID_SMS_UM_UNSENT,
    MENU_ID_SMS_UM_SENT,
    MENU_ID_SMS_BT_INBOX_VIEWER_OPT,
    MENU_ID_SMS_BT_OUTBOX_VIEWER_OPT,
    MENU_ID_SMS_BT_SENT_FAIL_VIEWER_OPT,
    MENU_ID_SMS_BT_DRAFT_VIEWER_OPT,
    MENU_ID_SMS_BT_VIEWER_OPT_REPLY,
    MENU_ID_SMS_BT_VIEWER_OPT_DELETE,
    MENU_ID_SMS_BT_VIEWER_OPT_FORWARD,
    MENU_ID_SMS_BT_VIEWER_OPT_EDIT,
    MENU_ID_SMS_BT_VIEWER_CALL_SENDER,
    MENU_ID_SMS_BT_VIEWER_OPT_RESEND,
    MENU_ID_SMS_BT_VIEWER_OPT_DETAIL,
    MENU_ID_SMS_BT_EDITOR_OPTIONS,
    MENU_ID_SMS_BT_ED_OPT_SEND_TO,
    MENU_ID_SMS_BT_ED_OPT_SAVE_TO_DRAFTS,
    MENU_ID_SMS_BT_ED_EDIT,
    MENU_ID_SMS_BT_ED_SAVE_TO,
    MMI_RP_APP_SMSBTUNIFIEDMESSAGE_MENU_MAX
}mmi_rp_app_smsbtunifiedmessage_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_SMS_UM_BT_MAIN_MENU_MESSAGES_TEXT = 48307 + 1, /* BASE_ID + 1 */
    STR_SMS_UM_BT_INBOX_ID,
    STR_SMS_UM_BT_WRITE_MSG_ID,
    STR_SMS_UM_BT_SENT_ID,
    STR_SMS_UM_BT_DRAFTS_ID,
    STR_SMS_UM_BT_SEND_FAILED_MSG,
    STR_ID_SMS_BT_REPLY_BY_SMS,
    STR_ID_SMS_BT_DELETE,
    STR_ID_SMS_BT_FORWARD,
    STR_ID_SMS_BT_SEND_TO,
    STR_ID_SMS_BT_SAVE,
    STR_ID_SMS_BT_CALL_SENDER,
    STR_ID_SMS_BT_NEW_MESSAGE,
    STR_ID_SMS_BT_RMOT_NOT_SUPPORT,
    STR_ID_SMS_BT_NO_CONN,
    STR_ID_SMS_BT_CONN,
    STR_ID_SMS_BT_FROM,
    STR_ID_SMS_BT_CREATION_DATE,
    STR_ID_SMS_BT_RECEIVE_DATE,
    STR_ID_SMS_BT_TYPE,
    STR_ID_SMS_BT_DELIVERY_STATUS,
    STR_ID_SMS_BT_STORAGE,
    STR_ID_SMS_BT_MESSAGE_MENUENTRY,
    STR_ID_SRV_BT_EMPTY_SUBJECT,
    STR_ID_SRV_BT_SMS_TEMPLATE,
    STR_ID_SRV_SMS_TEMPLATE,
    STR_ID_SRV_BT_SMS_TEMPLATE_1,
    STR_ID_SRV_BT_SMS_TEMPLATE_2,
    STR_ID_SRV_BT_SMS_TEMPLATE_3,
    STR_ID_SRV_BT_SMS_TEMPLATE_4,
    STR_ID_SRV_BT_SMS_TEMPLATE_5,
    STR_ID_SRV_BT_SMS_TEMPLATE_6,
    STR_ID_SRV_BT_SMS_TEMPLATE_7,
    STR_ID_SRV_BT_SMS_TEMPLATE_8,
    STR_ID_SRV_BT_SMS_TEMPLATE_9,
    STR_ID_SRV_BT_SMS_TEMPLATE_10,
    STR_ID_SRV_BT_SMS_CALL_SENDER,
    STR_ID_SRV_BT_SMS_SINGLE_NEW_MSG,
    STR_ID_SRV_BT_SMS_MULTI_NEW_MSG,
    STR_ID_SRV_BT_SMS_NEW_MSG_CHECK,
    STR_ID_SRV_BT_SMS_NEW_MSG_SUFFIX,
    STR_ID_SRV_BT_SMS_NEW_MSG_DISMISS,
    MMI_RP_APP_SMSBTUNIFIEDMESSAGE_STR_MAX
}mmi_rp_app_smsbtunifiedmessage_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_SMS_UM_BT_MAIN = 48307 + 1, /* BASE_ID + 1 */
    SCR_ID_SMS_UM_BT_MAIN_MESSAGE,
    SCR_ID_SMS_UM_BT_WRITE_MSG,
    SCR_ID_SMS_UM_BT_PROCESSING,
    SCR_ID_SMS_UM_BT_FOLDER,
    SCR_ID_SMS_BT_SENDER,
    SCR_ID_SMS_BT_EDITOR,
    SCR_ID_SMS_BT_VIEWER,
    SCR_ID_SMS_BT_PROCESSING,
    SCR_ID_SMS_BT_DETAIL,
    SCR_ID_SMS_BT_CONNECT_CHECK,
    SCR_ID_SMS_BT_FAIL_CONFIM,
    SCR_ID_SMS_BT_FAIL_RETRY_CONFIM,
    SCR_ID_SMS_BT_CONNECT_CONFIM,
    GRP_ID_SMS_BT_CONFIM,
    SCR_ID_SMS_BT_TEMPLATE,
    SCR_ID_SMS_BT_DELETE_MSG_CONFIM,
    GRP_ID_SMS_BT_DELETE_MSG_CONFIM,
    GRP_ID_SMS_BT_NEW_MSG,
    SCR_ID_SMS_BT_NEW_MSG,
    MMI_RP_APP_SMSBTUNIFIEDMESSAGE_SCR_MAX
}mmi_rp_app_smsbtunifiedmessage_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    SMS_BT_TIMER_ID = 48307 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_SMSBTUNIFIEDMESSAGE_TIMER_MAX
}mmi_rp_app_smsbtunifiedmessage_timer_enum;
/******************** Timer resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_MMI_SMS_UM_BT_REFRESH = 48307 + 1, /* BASE_ID + 1 */
    EVT_ID_MMI_SMS_UM_BT_ENTRY_MAIN_MSG,
    EVT_ID_MMI_SMS_UM_BT_ENTRY_FOLDER,
    MMI_RP_APP_SMSBTUNIFIEDMESSAGE_EVENT_MAX
}mmi_rp_app_smsbtunifiedmessage_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    MAIN_MENU_SMS_BT_MESSAGES_ICON = 48307 + 1, /* BASE_ID + 1 */
    IMG_SMS_UM_WRITE_MSG_ICON,
    IMG_SMS_UM_INBOX_ICON,
    IMG_SMS_UM_DRAFTS_MSG_ICON,
    IMG_SMS_UM_SEND_FAILED_MSG_ICON,
    IMG_SMS_UM_SENT_ICON,
    MMI_RP_APP_SMSBTUNIFIEDMESSAGE_IMG_MAX
}mmi_rp_app_smsbtunifiedmessage_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_SMSBTUNIFIEDMESSAGE_DEF_H */
