/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_audio_player_bt_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_AUDIO_PLAYER_BT_DEF_H
#define _MMI_RP_APP_AUDIO_PLAYER_BT_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_BT_MUSIC_TITLE = 36265 + 1, /* BASE_ID + 1 */
    STR_ID_BT_MUSIC_CONN_FAILED,
    STR_ID_BT_MUSIC_DISCONNECT_CONFIRM,
    STR_ID_BT_MUSIC_DISCONNECTING,
    STR_ID_BT_MUSIC_UNSUPPORT,
    STR_ID_OPTION_LOCAL_MUSIC,
    STR_ID_BT_MUSIC_NO_CONN,
    STR_ID_BT_MUSIC_IN_WEACTCH,
    STR_ID_BT_MUSIC_PLAY_FORBID,
    STR_ID_BT_MUSIC_FAIL_SYNC,
    STR_ID_BT_MUSIC_RETRY,
    STR_ID_BT_MUSIC_NO_CONTACT,
    MMI_RP_APP_AUDIO_PLAYER_BT_STR_MAX
}mmi_rp_app_audio_player_bt_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_BT_MUSIC_APP = 36265 + 1, /* BASE_ID + 1 */
    SCR_ID_BT_MUSIC_APP,
    SCR_ID_BT_MUSIC_DEVICE_LIST,
    SCR_ID_BT_MUSIC_CONN_SCREEN,
    SCR_ID_BT_MUSIC_CLOSE_CONFIRM,
    SCR_ID_BT_MUSIC_CLOSE_WAITING,
    SCR_ID_BT_MUSIC_CONNECT,
    SCR_ID_BT_MUSIC_RECONNECT,
    SCR_ID_BT_MUSIC_DIMMED_SCREEN,
    MMI_RP_APP_AUDIO_PLAYER_BT_SCR_MAX
}mmi_rp_app_audio_player_bt_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    BT_MUSIC_SEEKING_TIMER = 36265 + 1, /* BASE_ID + 1 */
    BT_MUSIC_SYNC_POS_TIMER,
    BT_MUSIC_STATUS_ICON_TIMER,
    BT_MUSIC_STREAM_TIMER,
    BT_MUSIC_AVRCP_TRACK_CHANGE_TIMER,
    BT_MUSIC_TITLE_DISPLAY_DELAY_TIMER,
    WR_BT_MUSIC_VOL_BAR_TIMER,
    MMI_RP_APP_AUDIO_PLAYER_BT_TIMER_MAX
}mmi_rp_app_audio_player_bt_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/


/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_BT_MUSIC = 36265 + 1, /* BASE_ID + 1 */               /*         BYTE */ 
    MMI_RP_APP_AUDIO_PLAYER_BT_MMI_CACHE_MAX
} mmi_rp_app_audio_player_bt_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_BG = 36265 + 1, /* BASE_ID + 1 */
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PREV,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_NEXT,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PAUSE,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY_PAUSE,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_UP,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_DOWN,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PREV_DIM,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_NEXT_DIM,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY_DIM,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PAUSE_DIM,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_UP_DIM,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_DOWN_DIM,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PREV_D,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PREV_P,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_NEXT_D,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_NEXT_P,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY_PAUSE_D,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY_PAUSE_P,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_UP_D,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_UP_P,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_DOWN_D,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_VOL_DOWN_P,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY_N,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY_D,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PLAY_P,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PAUSE_P,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PAUSE_D,
    IMG_ID_WR_BT_MUSIC_MAIN_SKIN1_PAUSE_N,
    MMI_RP_APP_AUDIO_PLAYER_BT_IMG_MAX
}mmi_rp_app_audio_player_bt_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_AUDIO_PLAYER_BT_DEF_H */
