/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_smsbtunifiedmessage.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_smsbtunifiedmessage_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "MainMenuDef.h"
#include "mmi_rp_app_mainmenu_def.h"
#include "WapResDef.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_smsbtunifiedmessage_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_smsbtunifiedmessage_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_smsbtunifiedmessage_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_SMS_BT_MESSAGES_MENUID,
        0,
        5,
        MENU_ID_SMS_UM_WRITE_MSG,
        MENU_ID_SMS_UM_INBOX,
        MENU_ID_SMS_UM_DRAFT,
        MENU_ID_SMS_UM_UNSENT,
        MENU_ID_SMS_UM_SENT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        STR_ID_SMS_UM_BT_MAIN_MENU_MESSAGES_TEXT,
        MAIN_MENU_SMS_BT_MESSAGES_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_UM_WRITE_MSG,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_SMS_UM_BT_WRITE_MSG_ID,
        IMG_SMS_UM_WRITE_MSG_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_UM_INBOX,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_SMS_UM_BT_INBOX_ID,
        IMG_SMS_UM_INBOX_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_UM_DRAFT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_SMS_UM_BT_DRAFTS_ID,
        IMG_SMS_UM_INBOX_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_UM_UNSENT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_SMS_UM_BT_SEND_FAILED_MSG,
        IMG_SMS_UM_INBOX_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_UM_SENT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_SMS_UM_BT_SENT_ID,
        IMG_SMS_UM_INBOX_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_INBOX_VIEWER_OPT,
        0,
        5,
        MENU_ID_SMS_BT_VIEWER_OPT_REPLY,
        MENU_ID_SMS_BT_VIEWER_OPT_FORWARD,
        MENU_ID_SMS_BT_VIEWER_CALL_SENDER,
        MENU_ID_SMS_BT_VIEWER_OPT_DELETE,
        MENU_ID_SMS_BT_VIEWER_OPT_DETAIL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_OUTBOX_VIEWER_OPT,
        0,
        3,
        MENU_ID_SMS_BT_VIEWER_OPT_FORWARD,
        MENU_ID_SMS_BT_VIEWER_OPT_DELETE,
        MENU_ID_SMS_BT_VIEWER_OPT_DETAIL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_SENT_FAIL_VIEWER_OPT,
        0,
        2,
        MENU_ID_SMS_BT_VIEWER_OPT_DELETE,
        MENU_ID_SMS_BT_VIEWER_OPT_DETAIL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_DRAFT_VIEWER_OPT,
        0,
        2,
        MENU_ID_SMS_BT_VIEWER_OPT_EDIT,
        MENU_ID_SMS_BT_VIEWER_OPT_DELETE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_VIEWER_OPT_REPLY,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_SMS_BT_REPLY_BY_SMS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_VIEWER_OPT_DELETE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_SMS_BT_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_VIEWER_OPT_FORWARD,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_SMS_BT_FORWARD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_VIEWER_OPT_EDIT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_EDIT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_VIEWER_CALL_SENDER,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_SMS_BT_CALL_SENDER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_VIEWER_OPT_RESEND,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_RESEND,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_VIEWER_OPT_DETAIL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DETAILS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_EDITOR_OPTIONS,
        0,
        2,
        MENU_ID_SMS_BT_ED_OPT_SEND_TO,
        MENU_ID_SMS_BT_ED_OPT_SAVE_TO_DRAFTS,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_ED_OPT_SEND_TO,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_SMS_BT_SEND_TO,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_ED_OPT_SAVE_TO_DRAFTS,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_SMS_BT_SAVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_ED_EDIT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_EDIT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SMS_BT_ED_SAVE_TO,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SAVE,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_SMS_BT_MESSAGES_MENUID, highlight_mainmenu_phonebook);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
