/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_phonesetting_new.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_phonesetting_new_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalMenuItems.h"
#include "mmi_rp_srv_wallpaper_def.h"
#include "mmi_rp_srv_flight_mode_def.h"
#include "mmi_rp_srv_phnset_onoff_def.h"
#include "mmi_rp_srv_screensaver_def.h"
#include "mmi_rp_srv_spof_def.h"
#include "mmi_rp_app_nitz_def.h"
#include "mmi_rp_srv_editor_def.h"
#include "mmi_rp_app_ntp_def.h"
#include "mmi_rp_srv_mmi_theme_def.h"
#include "mmi_rp_app_gpio_def.h"
#include "GlobalResDef.h"
#include "mmi_rp_app_scr_locker_def.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_phonesetting_new_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_phonesetting_new_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_phonesetting_new_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU9102_INITIAL_SETUP,
        0,
        9,
        MENU9141_TIME_AND_DATE,
        MENU_SETTING_LANGUAGE,
        MENU_PHNSET_BACKLIGHT_DISP,
        MENU_ITEM_IME_SETTING,
        MENU_IDLE_SCR_DISP,
        MENU_ID_NITZ_APP,
        MENU_ID_NTP_APP,
        MENU_SETTING_FLIGHT_MODE,
        MENU_ID_PHNSET_GPIO_SETTING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        STR_MENU9102_INITIAL_SETUP,
        IMG_SETTING_PHONE));

    ADD_APPLICATION_MENUITEM5((
        MENU_SETTING_LANGUAGE,
        MENU9102_INITIAL_SETUP,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_MENU_LANGUAGE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_PHNSET_BACKLIGHT_DISP,
        MENU9102_INITIAL_SETUP,
        3,
        MENU_ID_MAIN_MENU_STYLE,
        MENU_ID_BACK_LIGHT_BRIGHTNESS,
        MENU_ID_SCREEN_TIME_OUT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_BACK_LIGHT_DISP,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MAIN_MENU_STYLE,
        MENU_PHNSET_BACKLIGHT_DISP,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_MAIN_MENU_STYLE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_BACK_LIGHT_BRIGHTNESS,
        MENU_PHNSET_BACKLIGHT_DISP,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_BACK_LIGHT_BRIGHNESS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SCREEN_TIME_OUT,
        MENU_PHNSET_BACKLIGHT_DISP,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_SCREEN_TIME_OUT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU9141_TIME_AND_DATE,
        0,
        5,
        MENU_ID_CLOCK_TYPE,
        MENU9142_SETHOMECITY,
        MENU9143_SETTIMEANDDATE,
        MENU9144_SETTIMEANDDATEFORMAT,
        MENU_ID_TZ_CHANGE_DATETIME,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_MENU9141_TIME_AND_DATE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOCK_TYPE,
        MENU9141_TIME_AND_DATE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_PHONE_SETTING_CLOCK_TYPE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU9143_SETTIMEANDDATE,
        MENU9141_TIME_AND_DATE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PHNSET_SET_DT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU9144_SETTIMEANDDATEFORMAT,
        MENU9141_TIME_AND_DATE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_MENU9144_SETTIMEANDDATEFORMAT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TZ_CHANGE_DATETIME,
        MENU9141_TIME_AND_DATE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TZ_CHANGE_DATETIME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU9142_SETHOMECITY,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_MENU9142_SETHOMECITY,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_IDLE_SCR_DISP,
        0,
        3,
        MENU_SETTING_WALLPAPER,
        MENU_ID_SLK_TIME_SETTING_MENU,
        MENU_SETTING_SHOW_DT_TIME,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_IDLE_SCR_DISP,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_SETTING_SHOW_DT_TIME,
        MENU_IDLE_SCR_DISP,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_SETTING_SHOW_DT_TIME,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU9102_INITIAL_SETUP, HighlightPhnsetScr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_PHNSET_BACKLIGHT_DISP, HighlightDisplayScr);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
