/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_bluetooth.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_bluetooth_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "ConnectivityResDef.h"
#include "GlobalResDef.h"
#include "MainMenuDef.h"
#include "mmi_rp_app_mainmenu_def.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_bluetooth_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_bluetooth_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_bluetooth_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_POWER,
        MENU_CONN_BT_MAIN,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_BT_POWER,
        IMG_BT_POWER));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SCH_AUDIO_DEV,
        MENU_CONN_BT_MAIN,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_BT_SCH_AUD_DEV,
        IMG_BT_SCH_AUD_DEV));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SET_AUDIO_PATH_PHONE,
        MENU_CONN_BT_SET_AUDIO_PATH,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_BT_DEV_SET_AUDIO_PATH_PHONE,
        IMG_BT_SET_AUDIO_PATH_PHONE));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SET_AUDIO_PATH_HF,
        MENU_CONN_BT_SET_AUDIO_PATH,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_BT_DEV_SET_AUDIO_PATH_HF,
        IMG_BT_SET_AUDIO_PATH_HF));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SET_DEV_ADDR,
        MENU_CONN_BT_SET,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_BT_DEV_SET_DEV_ADDR,
        IMG_BT_SET_DEV_ADDR));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SET_STORAGE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_STORAGE,
        IMG_BT_SET_STORAGE));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SET_AUDIO_PATH,
        MENU_CONN_BT_SET,
        2,
        MENU_CONN_BT_SET_AUDIO_PATH_PHONE,
        MENU_CONN_BT_SET_AUDIO_PATH_HF,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_BT_DEV_SET_AUDIO_PATH,
        IMG_BT_SET_AUDIO_PATH));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SET_VIS,
        MENU_CONN_BT_MAIN,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_BT_DEV_SET_VIS,
        IMG_BT_SET_VIS));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_SET,
        MENU_CONN_BT_MAIN,
        2,
        MENU_CONN_BT_SET_AUDIO_PATH,
        MENU_CONN_BT_SET_DEV_ADDR,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_GLOBAL_ADVANCED,
        IMG_BT_SET));

    ADD_APPLICATION_MENUITEM5((
        MENU_CONN_BT_MAIN,
        0,
        4,
        MENU_CONN_BT_POWER,
        MENU_CONN_BT_SET_VIS,
        MENU_CONN_BT_SCH_AUDIO_DEV,
        MENU_CONN_BT_SET,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_BT_SWATCH_SETTING,
        IMG_BT_MENU_TITLE));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_CONN_BT_MAIN, mmi_bt_main_hilight_handler);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
