/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 * bt_adp_cust.h
 *
 * Project:
 * --------
 *   BT Project
 *
 * Description:
 * ------------
 *   This file is used to customization bt host
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef __BT_ADP_CUST_H__
#define __BT_ADP_CUST_H__

#ifdef BTMTK_ON_MAUI
#include "bt_feature.h"
#endif

typedef unsigned int DEV_ID;

typedef enum
{
    CUSTID_PAGE_TIMEOUT = 0,
    CUSTID_CONNECTION_TIMEOUT,
    CUSTID_INQUIRY_SCAN_WINDOW,
    CUSTID_INQUIRY_SCAN_INTERVAL,
    CUSTID_PAGE_SCAN_WINDOW,
    CUSTID_PAGE_SCAN_INTERVAL,
    CUSTID_SETUP_SYNC_CMD_RAWDATA,
    CUSTID_CREATE_CONN_ROLE_SWITCH_REQ,
    CUSTID_INQUIRY_LENGTH_ARRAY,
    CUSTID_PIN_PAIRING_REQ_TIMEOUT_ACTIVE,
    CUSTID_PIN_PAIRING_REQ_TIMEOUT_PASSIVE,
    CUSTID_SSP_PAIRING_REQ_TIMEOUT_ACTIVE,
    CUSTID_SSP_PAIRING_REQ_TIMEOUT_PASSIVE,
    CUSTID_SCO_PKT_TYPE,
    CUSTID_ESCO_PKY_TYPE,
    CUSTID_ROLE_SWITCH_RETRY_COUNT,
    CUSTID_GAP_INQUIRY_SHOW_ADDRESS,
    CUSTID_AUTO_ACCEPT_REQ_FROM_PAIRED_DEVICE,
    CUSTID_DELAY_AUTHENTICATION,
    CUSTID_DISABLE_INBAND_RINGTONE,
    CUSTID_CREATE_CONNECTION_RETRY_NO_EVENT_REPORTED,
    CUSTID_SSP_SUPPORTED,
    CUSTID_SSP_LOCAL_IOCAPABILITY,
    CUSTID_HFP_SDP_CACHE,
    CUSTID_HFP_SUPPORT_MASK,
    CUSTID_HFP_VOICE_RECOGNITION,
    CUSTID_HIGH_SPEED_SUPPORT,
    CUSTID_LE_SUPPORT,
    CUSTID_DEV_SUPPORT_SERVICES,
    CUSTID_SDP_DELAY_TIMEOUT,
    CUSTID_INQUIRY_TX_POWER,
    CUSTID_INQUIRY_LENGTH,
    CUSTID_INQUIRY_RESPONSE,
    CUSTID_NO_ROLE_SWITCH,
    CUSTID_KEEP_AWAKE_TIME,
    CUSTID_LE_INITIATE_INTERVAL,
    CUSTID_LE_INITIATE_WINDOW,
    CUSTID_LE_SCAN_INTERVAL,
    CUSTID_LE_SCAN_WINDOW,
    CUSTID_LE_CONN_INTERVAL_MIN,
    CUSTID_LE_CONN_INTERVAL_MAX,
    CUSTID_LE_CONN_LATENCY,
    CUSTID_LE_SUPERVISION_TO,
    CUSTID_L2CAP_LOW_PRIORITY_MAX_ACCEPT_TIMEOUT_MS,
#if defined(__ENABLE_MANUFACTURE_INFO__)
    CUSTID_MANUFACTURE_ID,
    CUSTID_PRODUCT_ID,
#endif
#ifdef __ANTI_LOST_FEATURE__
    CUSTID_RSSITHRESHOLD_ID,
    CUSTID_RSSIINTERVAL_ID,
#endif
    NUM_OF_CUSTID
} CUST_ID;

void *btGetCustvalue(U32 id);
void *btGetDevCustvalue(const char *dev_name, U32 id);
void *btGetDevCustvalueById(U32 did, U32 id);
U32 btGetDevID(const char *dev_name);

#endif /* __BT_ADP_CUST_H__ */
