/* This file is automatically generated by venus_theme_generator.pl. Do not modify it. */

    #if !defined(__MTK_TARGET__)
    #define __align(x)
    #endif /* !defined(__MTK_TARGET__) */
    

#define MMI_VENUS_APP_ICON_TOTAL_COUNT 0


__align(4) static const U8* const g_mmi_venus_app_icon_data_array [] = {
	(U8*)0
};

