#ifndef __CUST_IMG_GROUP_DATA_HW_H_
#define __CUST_IMG_GROUP_DATA_HW_H_
#include "CustDataRes.h"
#include "ResCompressConfig.h"

#ifndef __MMI_RESOURCE_IMAGE_THIRD_ROM__
#ifdef __MMI_RESOURCE_LZMA_IMAGE_GROUP_COMPRESS__

#if ( !defined (__MTK_TARGET__) )
    #define __align(x)
#endif

extern const U8 image_group_0[];
extern const U8 image_group_1[];
extern const U8 image_group_2[];
extern const U8 image_group_3[];
extern const U8 image_group_4[];
extern const U8 image_group_5[];
extern const U8 image_group_6[];
extern const U8 image_group_7[];
extern const U8 image_group_8[];
extern const U8 image_group_9[];
extern const U8 image_group_10[];
extern const U8 image_group_11[];
extern const U8 image_group_12[];
extern const U8 image_group_13[];
extern const U8 image_group_14[];
extern const U8 image_group_15[];
extern const U8 image_group_16[];
extern const U8 image_group_17[];
extern const U8 image_group_18[];
extern const U8 image_group_19[];
extern const U8 image_group_20[];
extern const U8 image_group_21[];
extern const U8 image_group_22[];
extern const U8 image_group_23[];
extern const U8 image_group_24[];
extern const U8 image_group_25[];
extern const U8 image_group_26[];
extern const U8 image_group_27[];
extern const U8 image_group_28[];
extern const U8 image_group_29[];
extern const U8 image_group_30[];
extern const U8 image_group_31[];
extern const U8 image_group_32[];
extern const U8 image_group_33[];
extern const U8 image_group_34[];
extern const U8 image_group_35[];
extern const U8 image_group_36[];
extern const U8 image_group_37[];
extern const U8 image_group_38[];
extern const U8 image_group_39[];
extern const U8 image_group_40[];
extern const U8 image_group_41[];
extern const U8 image_group_42[];
extern const U8 image_group_43[];
extern const U8 image_group_44[];
extern const U8 image_group_45[];
extern const U8 image_group_46[];
extern const U8 image_group_47[];
extern const U8 image_group_48[];
extern const U8 image_group_49[];
extern const U8 image_group_50[];
extern const U8 image_group_51[];
extern const U8 image_group_52[];
extern const U8 image_group_53[];
extern const U8 image_group_54[];
extern const U8 image_group_55[];
extern const U8 image_group_56[];
extern const U8 image_group_57[];
extern const U8 image_group_58[];
extern const U8 image_group_59[];
extern const U8 image_group_60[];
extern const U8 image_group_61[];
extern const U8 image_group_62[];
extern const U8 image_group_63[];
extern const U8 image_group_64[];
extern const U8 image_group_65[];
extern const U8 image_group_66[];
extern const U8 image_group_67[];
extern const U8 image_group_68[];
extern const U8 image_group_69[];
extern const U8 image_group_70[];
extern const U8 image_group_71[];
extern const U8 image_group_72[];
extern const U8 image_group_73[];
extern const U8 image_group_74[];
extern const U8 image_group_75[];
extern const U8 image_group_76[];
extern const U8 image_group_77[];
extern const U8 image_group_78[];
extern const U8 image_group_79[];
extern const U8 image_group_80[];
extern const U8 image_group_81[];
extern const U8 image_group_82[];
extern const U8 image_group_83[];
extern const U8 image_group_84[];
extern const U8 image_group_85[];
extern const U8 image_group_86[];
extern const U8 image_group_87[];
extern const U8 image_group_88[];
extern const U8 image_group_89[];
extern const U8 image_group_90[];
extern const U8 image_group_91[];
extern const U8 image_group_92[];
extern const U8 image_group_93[];
extern const U8 image_group_94[];
extern const U8 image_group_95[];
extern const U8 image_group_96[];
extern const U8 image_group_97[];
extern const U8 image_group_98[];
extern const U8 image_group_99[];
extern const U8 image_group_100[];
extern const U8 image_group_101[];
extern const U8 image_group_102[];
extern const U8 image_group_103[];
extern const U8 image_group_104[];
extern const U8 image_group_105[];
extern const U8 image_group_106[];
extern const U8 image_group_107[];
extern const U8 image_group_108[];
extern const U8 image_group_109[];
extern const U8 image_group_110[];
extern const U8 image_group_111[];
extern const U8 image_group_112[];
extern const U8 image_group_113[];
extern const U8 image_group_114[];
extern const U8 image_group_115[];
extern const U8 image_group_116[];
extern const U8 image_group_117[];
extern const U8 image_group_118[];
extern const U8 image_group_119[];
extern const U8 image_group_120[];
extern const U8 image_group_121[];
extern const U8 image_group_122[];
extern const U8 image_group_123[];
extern const U8 image_group_124[];
extern const U8 image_group_125[];
extern const U8 image_group_126[];
extern const U8 image_group_127[];
extern const U8 image_group_128[];
extern const U8 image_group_129[];
extern const U8 image_group_130[];

#ifdef __MMI_RESOURCE_UT_SIMPLE_CACHE_SUPPORT__
extern U8 cache_image_group_0[];
extern U8 cache_image_group_1[];
extern U8 cache_image_group_2[];
extern U8 cache_image_group_3[];
extern U8 cache_image_group_4[];
extern U8 cache_image_group_5[];
extern U8 cache_image_group_6[];
extern U8 cache_image_group_7[];
extern U8 cache_image_group_8[];
extern U8 cache_image_group_9[];
extern U8 cache_image_group_10[];
extern U8 cache_image_group_11[];
extern U8 cache_image_group_12[];
extern U8 cache_image_group_13[];
extern U8 cache_image_group_14[];
extern U8 cache_image_group_15[];
extern U8 cache_image_group_16[];
extern U8 cache_image_group_17[];
extern U8 cache_image_group_18[];
extern U8 cache_image_group_19[];
extern U8 cache_image_group_20[];
extern U8 cache_image_group_21[];
extern U8 cache_image_group_22[];
extern U8 cache_image_group_23[];
extern U8 cache_image_group_24[];
extern U8 cache_image_group_25[];
extern U8 cache_image_group_26[];
extern U8 cache_image_group_27[];
extern U8 cache_image_group_28[];
extern U8 cache_image_group_29[];
extern U8 cache_image_group_30[];
extern U8 cache_image_group_31[];
extern U8 cache_image_group_32[];
extern U8 cache_image_group_33[];
extern U8 cache_image_group_34[];
extern U8 cache_image_group_35[];
extern U8 cache_image_group_36[];
extern U8 cache_image_group_37[];
extern U8 cache_image_group_38[];
extern U8 cache_image_group_39[];
extern U8 cache_image_group_40[];
extern U8 cache_image_group_41[];
extern U8 cache_image_group_42[];
extern U8 cache_image_group_43[];
extern U8 cache_image_group_44[];
extern U8 cache_image_group_45[];
extern U8 cache_image_group_46[];
extern U8 cache_image_group_47[];
extern U8 cache_image_group_48[];
extern U8 cache_image_group_49[];
extern U8 cache_image_group_50[];
extern U8 cache_image_group_51[];
extern U8 cache_image_group_52[];
extern U8 cache_image_group_53[];
extern U8 cache_image_group_54[];
extern U8 cache_image_group_55[];
extern U8 cache_image_group_56[];
extern U8 cache_image_group_57[];
extern U8 cache_image_group_58[];
extern U8 cache_image_group_59[];
extern U8 cache_image_group_60[];
extern U8 cache_image_group_61[];
extern U8 cache_image_group_62[];
extern U8 cache_image_group_63[];
extern U8 cache_image_group_64[];
extern U8 cache_image_group_65[];
extern U8 cache_image_group_66[];
extern U8 cache_image_group_67[];
extern U8 cache_image_group_68[];
extern U8 cache_image_group_69[];
extern U8 cache_image_group_70[];
extern U8 cache_image_group_71[];
extern U8 cache_image_group_72[];
extern U8 cache_image_group_73[];
extern U8 cache_image_group_74[];
extern U8 cache_image_group_75[];
extern U8 cache_image_group_76[];
extern U8 cache_image_group_77[];
extern U8 cache_image_group_78[];
extern U8 cache_image_group_79[];
extern U8 cache_image_group_80[];
extern U8 cache_image_group_81[];
extern U8 cache_image_group_82[];
extern U8 cache_image_group_83[];
extern U8 cache_image_group_84[];
extern U8 cache_image_group_85[];
extern U8 cache_image_group_86[];
extern U8 cache_image_group_87[];
extern U8 cache_image_group_88[];
extern U8 cache_image_group_89[];
extern U8 cache_image_group_90[];
extern U8 cache_image_group_91[];
extern U8 cache_image_group_92[];
extern U8 cache_image_group_93[];
extern U8 cache_image_group_94[];
extern U8 cache_image_group_95[];
extern U8 cache_image_group_96[];
extern U8 cache_image_group_97[];
extern U8 cache_image_group_98[];
extern U8 cache_image_group_99[];
extern U8 cache_image_group_100[];
extern U8 cache_image_group_101[];
extern U8 cache_image_group_102[];
extern U8 cache_image_group_103[];
extern U8 cache_image_group_104[];
extern U8 cache_image_group_105[];
extern U8 cache_image_group_106[];
extern U8 cache_image_group_107[];
extern U8 cache_image_group_108[];
extern U8 cache_image_group_109[];
extern U8 cache_image_group_110[];
extern U8 cache_image_group_111[];
extern U8 cache_image_group_112[];
extern U8 cache_image_group_113[];
extern U8 cache_image_group_114[];
extern U8 cache_image_group_115[];
extern U8 cache_image_group_116[];
extern U8 cache_image_group_117[];
extern U8 cache_image_group_118[];
extern U8 cache_image_group_119[];
extern U8 cache_image_group_120[];
extern U8 cache_image_group_121[];
extern U8 cache_image_group_122[];
extern U8 cache_image_group_123[];
extern U8 cache_image_group_124[];
extern U8 cache_image_group_125[];
extern U8 cache_image_group_126[];
extern U8 cache_image_group_127[];
extern U8 cache_image_group_128[];
extern U8 cache_image_group_129[];
extern U8 cache_image_group_130[];

#endif //__MMI_RESOURCE_UT_SIMPLE_CACHE_SUPPORT__


#endif  //__MMI_RESOURCE_LZMA_IMAGE_GROUP_COMPRESS__


#endif  // __MMI_RESOURCE_IMAGE_THIRD_ROM__

#endif//__CUST_IMG_GROUP_DATA_HW_H_
