/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_menu_misc_data.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/
#include "MMIDataType.h"
#include "CustMenuRes.h"
#include "mmi_rp_menu_misc_def.h"

/* Application specified header files for MainMenu/Image IDs declared elsewhere. */

/* Count of all main menu IDs */
const U32 mmi_rg_menu_mainmenuid_total = 18;

/* Array of Image IDs for main menu IDs */
/* 1) Main menu ID */
/* 2) List image ID */
/* 3) Matrix image ID */
/* 4) Page image ID */
/* 5) Venus1 image ID */
/* 6) Venus2 image ID */
/* 7) Matrix highlight image ID */
/* 8) Matrix controlled area image ID */
/* 9) Venus1 highlight image ID */
/* 10) Title image ID */
const mmi_rg_menu_mainmenu_img_id_struct mmi_rg_menu_mainmenu_img_id_array[] = {
    { 47530, 0, 0, 0, 0, 0, 0, 0, 0, 47565},
    { 47531, 0, 0, 0, 0, 0, 0, 0, 0, 47552},
    { 48359, 0, 0, 0, 0, 0, 0, 0, 0, 47554},
    { 48410, 0, 0, 0, 0, 0, 0, 0, 0, 47534},
    { 47532, 0, 0, 0, 0, 0, 0, 0, 0, 47555},
    { 47533, 0, 0, 0, 0, 0, 0, 0, 0, 47566},
    { 47534, 0, 0, 0, 0, 0, 0, 0, 0, 47563},
    { 47535, 0, 0, 0, 0, 0, 0, 0, 0, 47564},
    { 47536, 0, 0, 0, 0, 0, 0, 0, 0, 47562},
    { 47537, 0, 0, 0, 0, 0, 0, 0, 0, 47557},
    { 47539, 0, 0, 0, 0, 0, 0, 0, 0, 47558},
    { 47541, 0, 0, 0, 0, 0, 0, 0, 0, 47560},
    { 15313, 0, 0, 0, 0, 0, 0, 0, 0, 47561},
    { 47543, 0, 0, 0, 0, 0, 0, 0, 0, 47568},
    { 47544, 0, 0, 0, 0, 0, 0, 0, 0, 47569},
    { 47542, 0, 0, 0, 0, 0, 0, 0, 0, 47563},
    { 46971, 0, 0, 0, 0, 0, 0, 0, 0, 47553},
    { 39217, 0, 0, 0, 0, 0, 0, 0, 0, 47559},
};

/* Default menu ID associated parent with menu IDs */
/* Pair of 'parent menu ID', 'default menu ID' */
const mmi_rg_menu_default_struct mmi_rg_menu_default_menu_array[] = {
   {NULL, NULL}
};

/* Arrays of menu IDs for Group IDs */
const U16 menu_group_editor[] = {26102, 26103, 26104, 0xFFFF};
const U16 menu_group_editor_cui_options[] = {26106, 26107, 0xFFFF};

/* Menu group array associated with Group ID enum */
const U16 *mmi_rg_menu_group[] = {
    menu_group_editor,
    menu_group_editor_cui_options,
    NULL
};

/* Application's notify handlers */
const mmi_rg_notify_hdlr_struct mmi_frm_const_notify_handler_table[] = {
   {0, NULL}
};
