/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_native_app_package_data.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/


#include "MMIDataType.h"
#include "mmi_rp_native_app_package_data.h"
#include "mmi_rp_all_defs.h"
#include "GlobalResDef.h"

const srv_nativeappfactory_package_struct native_app_package_table[] = {
    {"native.mtk.bluetooth", NULL, (mmi_app_launch_func)mmi_bt_launch_bt, APP_BLUETOOTH, STR_BT_MENU_TITLE, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.imageviewer", NULL, (mmi_app_launch_func)mmi_imgview_launch, APP_IMAGEVIEWER, STR_ID_IMGVIEW_NAME, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.sndrec", NULL, (mmi_app_launch_func)mmi_sndrec_launch_function, APP_SOUNDRECORDER, STR_ID_SNDREC_MAIN, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.audioplayer", NULL, (mmi_app_launch_func)mmi_audply_entry_main, APP_AUDIOPLAYER, STR_ID_AUDPLY_TITLE, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.audioplayerbt", NULL, (mmi_app_launch_func)mmi_bt_music_entry_main, APP_BT_MUSIC, STR_ID_AUDPLY_BT_TITLE, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.worldclock", NULL, (mmi_app_launch_func)mmi_world_clock_launch, APP_WORLDCLOCK, STR_WORLD_CLOCK_TITLE, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.wlan", NULL, (mmi_app_launch_func)mmi_wlan_app_launch_func, APP_DATAACCOUNT, STR_ID_APP_DTCNT_WLAN, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.calllog", mmi_clog_appmgr_package_proc, (mmi_app_launch_func)mmi_clog_appmgr_launch, APP_CALLLOG, STR_ID_CLOG_CALL_LOG, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.btcalllog", NULL, (mmi_app_launch_func)mmi_clog_appmgr_launch_bt, APP_BTCALLLOG, STR_ID_CLOG_BT_CALL_LOG, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.profile", NULL, (mmi_app_launch_func)mmi_profiles_launch_function, APP_PROFILES, STR_ID_PROF_CAPTION, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.filemgr", NULL, (mmi_app_launch_func)mmi_fmgr_app_mgr_launch, APP_FILEMANAGER, STR_FMGR_TITLE, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.setting", NULL, (mmi_app_launch_func)EntryScrSettingMenu, APP_SETTING_NEW, MAIN_MENU_SETTINGS_TEXT, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.services_sat", NULL, (mmi_app_launch_func)mmi_service_sat_proc, APP_SERVICES_SAT, STR_ID_SAT_MENU_TITLE, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.calculator", NULL, (mmi_app_launch_func)CalcPreEntryApp, APP_CALCULATOR, STR_ID_CALC_MENU, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.alarm", NULL, (mmi_app_launch_func)EntryAlmMenu, APP_ALARM, STR_GLOBAL_ALARM, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.calendar", NULL, (mmi_app_launch_func)ClndrPreEntryApp, APP_CALENDAR, ORGANIZER_MENU_CALENDER_STRINGID, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.dialer", NULL, (mmi_app_launch_func)mmi_dialer_launch, APP_DIALER, STR_ID_DIALER_MENU, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.btdialer", NULL, (mmi_app_launch_func)mmi_btdialer_app_launch_func, APP_BT_DIALER, STR_ID_BT_DIALER_TITLE, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.videoplayer", NULL, (mmi_app_launch_func)mmi_vdoply_entry_app, APP_VDOPLY, STR_ID_VDOPLY_APP_NAME, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.messaging", mmi_um_package_proc, (mmi_app_launch_func)mmi_um_entry_main_message_menu, APP_UNIFIEDMESSAGE, STR_ID_UM_MAIN_MENU_MESSAGES_TEXT, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.btmessaging", NULL, (mmi_app_launch_func)mmi_um_entry_main_message_enter_bt_msg, APP_BT_UNIFIEDMESSAGE, STR_ID_BT_UM_MAIN_MENU_MESSAGES_TEXT, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.btnotification", NULL, (mmi_app_launch_func)mmi_bt_notification_launch, APP_BTNOTIFICATION, STR_ID_BTNOTIFICATION_APPLICATION_APP_NAME, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.btremotecapture", mmi_bt_rmtcap_package_proc, (mmi_app_launch_func)mmi_btrmtcap_entry_main_message_menu, APP_BTREMOTECAPTURE, STR_ID_BTRMTCAP_APPLICATION_APP_NAME, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.pxpapp", NULL, (mmi_app_launch_func)NULL, APP_PXPAPP, NULL, IMG_GLOBAL_DEFAULT, (MMI_BOOL)1},
    {"native.mtk.fmpapp", NULL, (mmi_app_launch_func)mmi_fmpapp_launch, APP_FMPAPP, STR_ID_FMP_MAINMENU, IMG_FMPAPP_ICON_ID, (MMI_BOOL)0},
    {"native.mtk.phonebook", NULL, (mmi_app_launch_func)mmi_phb_pre_entry_main_screen, APP_PHONEBOOK, STR_SCR_PBOOK_CAPTION, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.btphonebook", NULL, (mmi_app_launch_func)mmi_phb_bt_pre_entry_main_screen, APP_BTPHONEBOOK, STR_SCR_BT_PBOOK_CAPTION, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.mtk.connectivity", NULL, (mmi_app_launch_func)mmi_connectivity_app_launch_func, APP_CONNECTIVITY_MAINMENU, STR_ID_CONNECTIVITY_TEXT, IMG_GLOBAL_DEFAULT, (MMI_BOOL)0},
    {"native.guobi.winguo", NULL, (mmi_app_launch_func)vapp_winguo_launch, APP_GB_WINGUO, STR_GB_WINGUO_SMARTSEARCH, IMG_WG_WINGUO_NATIVE_ICON, (MMI_BOOL)1},
    {"native.guobi.winguo_net", NULL, (mmi_app_launch_func)GB_WG_Search_Net_Launch, APP_GB_WINGUO_NET, STR_GB_WINGUO_LOG, IMG_WG_WINGUO_NET_ICON, (MMI_BOOL)1},
};

U32 srv_nativeappfactory_get_table_size(void)
{
    return sizeof(native_app_package_table)/sizeof(srv_nativeappfactory_package_struct);
}
