/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_cache_table.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 * -------
 *
 *******************************************************************************/
/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/
#include "common_nvram_editor_data_item.h"
#define MMI_CACHE_BYTE_NUMBER 113
#define MMI_CACHE_SHORT_NUMBER 35
#define MMI_CACHE_DOUBLE_NUMBER 39


kal_uint16 mmi_rp_mmi_cache_get_byte_number(void)
{
    return MMI_CACHE_BYTE_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_short_number(void)
{
    return MMI_CACHE_SHORT_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_double_number(void)
{
    return MMI_CACHE_DOUBLE_NUMBER;
}


const kal_uint16 MMI_CACHE_BYTE_ENUM_TABLE[MMI_CACHE_BYTE_NUMBER] =
{
    26233,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
    35665,   /* 1 -- NVRAM_AUDPLY_BACKGROUND_PLAY */
    37535,   /* 2 -- NVRAM_WC_DST */
    35667,   /* 3 -- NVRAM_AUDPLY_LYRICS_DISPLAY */
    35661,   /* 4 -- NVRAM_AUDPLY_PREFER_LIST */
    27135,   /* 5 -- NVRAM_SETTING_LANG */
    26256,   /* 6 -- NVRAM_SETTING_PICTURE_QUALITY */
     9485,   /* 7 -- NVRAM_SMS_MISCELL_SETTING */
    27234,   /* 8 -- GPS_TIME_SYNC_MODE */
    26105,   /* 9 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
     4811,   /* 10 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    33468,   /* 11 -- NVRAM_BT_POWER_STATUS */
    32051,   /* 12 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    26289,   /* 13 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    45970,   /* 14 -- NVRAM_VDOPLY_PROXY_IP1 */
    45971,   /* 15 -- NVRAM_VDOPLY_PROXY_IP2 */
    45972,   /* 16 -- NVRAM_VDOPLY_PROXY_IP3 */
    45973,   /* 17 -- NVRAM_VDOPLY_PROXY_IP4 */
    35015,   /* 18 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    35664,   /* 19 -- NVRAM_AUDPLY_SHUFFLE */
    35670,   /* 20 -- NVRAM_AUDPLY_REMOVE_IN_PROCESS */
    39901,   /* 21 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    35663,   /* 22 -- NVRAM_AUDPLY_REPEAT */
    28292,   /* 23 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    37531,   /* 24 -- CURRENT_CITY */
    35660,   /* 25 -- NVRAM_AUDPLY_VOLUME */
    26104,   /* 26 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    26118,   /* 27 -- NVRAM_SETTING_HANDWRITING_ON */
    14510,   /* 28 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    39900,   /* 29 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    32052,   /* 30 -- NVRAM_SSC_DISABLE_FLAG */
    32054,   /* 31 -- NVRAM_SETTING_SPEED_DIAL */
    41126,   /* 32 -- RESTORE_DEFAULT_OWNER_NO */
     9592,   /* 33 -- NVRAM_CALLSET_QUICK_END_FLAG */
    26230,   /* 34 -- NVRAM_BYTE_LED_SETTING */
    35358,   /* 35 -- NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
    32042,   /* 36 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
    35666,   /* 37 -- NVRAM_AUDPLY_SPECTRUM_DISPLAY_STYLE */
    35662,   /* 38 -- NVRAM_AUDPLY_SKIN */
    26120,   /* 39 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    35671,   /* 40 -- NVRAM_AUDPLY_SINGLE_VOL */
     9591,   /* 41 -- NVRAM_CALLSET_REDIAL */
     7608,   /* 42 -- NVRAM_GPS_PAYLOAD_STORAGE */
    32047,   /* 43 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
     9590,   /* 44 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
     9484,   /* 45 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    30214,   /* 46 -- NVRAM_SRV_SNDREC_QUALITY */
    37532,   /* 47 -- FOREIGN_CITY */
    27130,   /* 48 -- TIME_FORMAT */
    27132,   /* 49 -- RESTORE_DEFAULT_TIME_FORMAT */
    37533,   /* 50 -- NVRAM_SETTING_DT_DST */
    26234,   /* 51 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    26122,   /* 52 -- NVRAM_PEN_COLOR */
    43274,   /* 53 -- RESTORE_DEFAULT_AUTOUPDATE_TIME */
    26121,   /* 54 -- NVRAM_PEN_SPEED */
    26116,   /* 55 -- NVRAM_SETTING_PEN_SPEED */
    26119,   /* 56 -- NVRAM_SETTING_PEN_WIDTH */
    26288,   /* 57 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    32053,   /* 58 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    41131,   /* 59 -- NVRAM_PHNSET_MAIN_MENU_STYLE */
    35659,   /* 60 -- NVRAM_AUDPLY_LIST_AUTO_GEN */
    26226,   /* 61 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    27131,   /* 62 -- DATE_FORMAT */
    27133,   /* 63 -- RESTORE_DEFAULT_DATE_FORMAT */
     7607,   /* 64 -- NRRAM_GPS_LOGGING_SWITCH */
    32044,   /* 65 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    32045,   /* 66 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    32046,   /* 67 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    26110,   /* 68 -- NVRAM_IME_INPUT_PATTERN */
    32043,   /* 69 -- NVRAM_PHB_STARTUP_COPY_SIM */
    41129,   /* 70 -- NVRAM_UPDATE_DATETIME_MODE */
     7765,   /* 71 -- NVRAM_PROFILES_LASTACTIVATED */
    26117,   /* 72 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    26231,   /* 73 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    44384,   /* 74 -- NVRAM_BT_SPEAKER */
    45968,   /* 75 -- NVRAM_VDOPLY_VOLUMN */
    41125,   /* 76 -- NVRAM_SETTING_OWNER_NO */
     9588,   /* 77 -- NVRAM_CALLSET_CTR_MODE */
    37537,   /* 78 -- NVRAM_DOWNLOAD_CITY1 */
    37538,   /* 79 -- NVRAM_DOWNLOAD_CITY2 */
    15319,   /* 80 -- NVRAM_DEFAULT_USB_APP */
    30139,   /* 81 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    26102,   /* 82 -- NVRAM_IME_SMART_MODE_CONFIG */
    27134,   /* 83 -- NVRAM_DT_SEP_FORMAT */
    18166,   /* 84 -- BT_BQB_TEST */
    26225,   /* 85 -- NVRAM_SETTING_CONTRAST_LEVEL */
    26108,   /* 86 -- NVRAM_IME_VIBRATION_FLAG */
    36266,   /* 87 -- NVRAM_BT_MUSIC */
    26106,   /* 88 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    30213,   /* 89 -- NVRAM_SRV_SNDREC_STORAGE */
    45969,   /* 90 -- NVRAM_VDOPLY_ACTIVE_PROFILE_IDX */
    27088,   /* 91 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    26109,   /* 92 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    26287,   /* 93 -- NVRAM_NETSET_PREFERRED_MODE */
    26229,   /* 94 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    33466,   /* 95 -- NVRAM_BT_RECEIVE_DRIVE */
    30215,   /* 96 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    26228,   /* 97 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    33467,   /* 98 -- NVRAM_BT_RECEIVE_DRIVE_ASK */
    28291,   /* 99 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    26227,   /* 100 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    27235,   /* 101 -- SRV_DT_TIME_ZONE */
    41127,   /* 102 -- NVRAM_SETTING_STATUS_DT_TIME */
     7764,   /* 103 -- NVRAM_PROFILES_ACTIVATED */
    45974,   /* 104 -- NVRAM_VDOPLY_PROXY_ON_OFF */
    26103,   /* 105 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    26107,   /* 106 -- NVRAM_IME_AUTO_SPACE_FLAG */
    32228,   /* 107 -- NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
    11577,   /* 108 -- NVRAM_IDLE_SWATCH_INDEX */
    26235,   /* 109 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    41128,   /* 110 -- NVRAM_AUTOUPDATE_DT_STATUS */
    28322,   /* 111 -- NVRAM_IDLE_DIALER_TTS_SETTING */
     9589,   /* 112 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint16 MMI_CACHE_SHORT_ENUM_TABLE[MMI_CACHE_SHORT_NUMBER] =
{
    26111,   /* 0 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
    45977,   /* 1 -- NVRAM_VDOPLY_OPTION_BRIGHTNESS */
     9486,   /* 2 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    40101,   /* 3 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    26113,   /* 4 -- NVRAM_SETTING_WRITING_LANG */
    40100,   /* 5 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
    45976,   /* 6 -- NVRAM_VDOPLY_STORAGE */
     9594,   /* 7 -- NVRAM_CALLSET_QUICK_END_TIME */
    32048,   /* 8 -- NVRAM_PHB_STORAGE_LOCATION */
    37536,   /* 9 -- NVRAM_FRN_TIMEZONE */
    26112,   /* 10 -- RESTORE_PREFER_INPUT_METHOD */
    39905,   /* 11 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    26232,   /* 12 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    45979,   /* 13 -- NVRAM_VDOPLY_OPTION_REPEAT */
    32050,   /* 14 -- NVRAM_PHB_VCARD_VERSION */
    26115,   /* 15 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    45975,   /* 16 -- NVRAM_VDOPLY_SNAPSHOT_SEQ_NO */
    40099,   /* 17 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    32049,   /* 18 -- NVRAM_PHB_NAME_LIST_FILTER */
    33917,   /* 19 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
     9593,   /* 20 -- NVRAM_CALLSET_CTR_TIME */
    35668,   /* 21 -- NVRAM_AUDPLY_LAST_PLAYLIST_INDEX */
    39903,   /* 22 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    37534,   /* 23 -- NVRAM_TIMEZONE */
    45980,   /* 24 -- NVRAM_VDOPLY_OPTION_PLAY_MODE */
    40098,   /* 25 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    26114,   /* 26 -- NVRAM_SETTING_WRITING_LANG_SUB */
    35016,   /* 27 -- NVRAM_IMGVIEW_STORAGE */
    45981,   /* 28 -- NVRAM_VDOPLY_STREAM_SEQ_NO */
    45978,   /* 29 -- NVRAM_VDOPLY_OPTION_CONTRAST */
    33918,   /* 30 -- NVRAM_BT_DIALER_FIRST_BOOT */
    32055,   /* 31 -- NVRAM_PHB_PBAPC_NAME_ORDER */
    35669,   /* 32 -- NVRAM_AUDIO_SPEED_VALUE */
    39902,   /* 33 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    39904,   /* 34 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint16 MMI_CACHE_DOUBLE_ENUM_TABLE[MMI_CACHE_DOUBLE_NUMBER] =
{
    12116,   /* 0 -- NVRAM_AUDIO_DEBUG_INFO1 */
    12117,   /* 1 -- NVRAM_AUDIO_DEBUG_INFO2 */
    12118,   /* 2 -- NVRAM_AUDIO_DEBUG_INFO3 */
    12119,   /* 3 -- NVRAM_AUDIO_DEBUG_INFO4 */
    41130,   /* 4 -- NVRAM_RTC_TIME */
    39899,   /* 5 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    45982,   /* 6 -- NVRAM_VDOPLY_PROXY_PORT */
    27099,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    27100,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    27101,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    27102,   /* 10 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    27103,   /* 11 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    27104,   /* 12 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    27105,   /* 13 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    27106,   /* 14 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    39897,   /* 15 -- NARAM_DISPCHAR_AVATAR_ONOFF */
     4803,   /* 16 -- NVRAM_MRE_SRV_DA_SIM1 */
     4805,   /* 17 -- NVRAM_MRE_SRV_DA_SIM2 */
     4807,   /* 18 -- NVRAM_MRE_SRV_DA_SIM3 */
     4809,   /* 19 -- NVRAM_MRE_SRV_DA_SIM4 */
     9372,   /* 20 -- NVRAM_WLAN_RECONN_PROF_ID */
    39896,   /* 21 -- NVRAM_DISPCHAR_AVATAR_WPSS */
    45984,   /* 22 -- NVRAM_VDOPLY_LOWEST_UDP_PORT */
     7766,   /* 23 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    45983,   /* 24 -- NVRAM_VDOPLY_HIGHEST_UDP_PORT */
    27107,   /* 25 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    27108,   /* 26 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    27109,   /* 27 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    27110,   /* 28 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    27111,   /* 29 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    27112,   /* 30 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    27113,   /* 31 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    27114,   /* 32 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    39898,   /* 33 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
     4804,   /* 34 -- NVRAM_MRE_SRV_DA_SIM1_PX */
     4806,   /* 35 -- NVRAM_MRE_SRV_DA_SIM2_PX */
     4808,   /* 36 -- NVRAM_MRE_SRV_DA_SIM3_PX */
     4810,   /* 37 -- NVRAM_MRE_SRV_DA_SIM4_PX */
    47530,   /* 38 -- NVRAM_MAINMENU_HIGHLIGHT_INDEX */
};



const kal_uint32 NVRAM_EF_MMI_CACHE_BYTE_KEY_DEFAULT[NVRAM_MMI_CACHE_BYTE_KEY_SIZE * NVRAM_MMI_CACHE_BYTE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x0033E086,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
    0x02FDC3F3,   /* 1 -- NVRAM_AUDPLY_BACKGROUND_PLAY */
    0x0588B0F2,   /* 2 -- NVRAM_WC_DST */
    0x058BF549,   /* 3 -- NVRAM_AUDPLY_LYRICS_DISPLAY */
    0x07F298BB,   /* 4 -- NVRAM_AUDPLY_PREFER_LIST */
    0x0C5FC9DD,   /* 5 -- NVRAM_SETTING_LANG */
    0x1047E32F,   /* 6 -- NVRAM_SETTING_PICTURE_QUALITY */
    0x10FD69C4,   /* 7 -- NVRAM_SMS_MISCELL_SETTING */
    0x13774D01,   /* 8 -- GPS_TIME_SYNC_MODE */
    0x14915C3B,   /* 9 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
    0x14F6111C,   /* 10 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    0x15654019,   /* 11 -- NVRAM_BT_POWER_STATUS */
    0x19F031B5,   /* 12 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    0x21246C43,   /* 13 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    0x22D82416,   /* 14 -- NVRAM_VDOPLY_PROXY_IP1 */
    0x22D82417,   /* 15 -- NVRAM_VDOPLY_PROXY_IP2 */
    0x22D82418,   /* 16 -- NVRAM_VDOPLY_PROXY_IP3 */
    0x22D82419,   /* 17 -- NVRAM_VDOPLY_PROXY_IP4 */
    0x2322B5A4,   /* 18 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    0x23E13D27,   /* 19 -- NVRAM_AUDPLY_SHUFFLE */
    0x24E3F49E,   /* 20 -- NVRAM_AUDPLY_REMOVE_IN_PROCESS */
    0x25031C82,   /* 21 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    0x2891358D,   /* 22 -- NVRAM_AUDPLY_REPEAT */
    0x2A9FDCAF,   /* 23 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    0x2E994CA8,   /* 24 -- CURRENT_CITY */
    0x2FEFEF0C,   /* 25 -- NVRAM_AUDPLY_VOLUME */
    0x338FF87D,   /* 26 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    0x33E27B20,   /* 27 -- NVRAM_SETTING_HANDWRITING_ON */
    0x33E2BC2F,   /* 28 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    0x3617F479,   /* 29 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    0x3911329F,   /* 30 -- NVRAM_SSC_DISABLE_FLAG */
    0x3F180537,   /* 31 -- NVRAM_SETTING_SPEED_DIAL */
    0x410A8A93,   /* 32 -- RESTORE_DEFAULT_OWNER_NO */
    0x4214065D,   /* 33 -- NVRAM_CALLSET_QUICK_END_FLAG */
    0x455E5A65,   /* 34 -- NVRAM_BYTE_LED_SETTING */
    0x495D7ACE,   /* 35 -- NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
    0x4AC1FB21,   /* 36 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
    0x4D0DF3B8,   /* 37 -- NVRAM_AUDPLY_SPECTRUM_DISPLAY_STYLE */
    0x59D145EF,   /* 38 -- NVRAM_AUDPLY_SKIN */
    0x5A4072DE,   /* 39 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    0x5C355B2E,   /* 40 -- NVRAM_AUDPLY_SINGLE_VOL */
    0x5C5012DE,   /* 41 -- NVRAM_CALLSET_REDIAL */
    0x5EA03F95,   /* 42 -- NVRAM_GPS_PAYLOAD_STORAGE */
    0x605F66F6,   /* 43 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
    0x613F6FD6,   /* 44 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
    0x61D48B89,   /* 45 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    0x62CC3DCF,   /* 46 -- NVRAM_SRV_SNDREC_QUALITY */
    0x63D46A2D,   /* 47 -- FOREIGN_CITY */
    0x655C92B2,   /* 48 -- TIME_FORMAT */
    0x66FB6043,   /* 49 -- RESTORE_DEFAULT_TIME_FORMAT */
    0x670179A5,   /* 50 -- NVRAM_SETTING_DT_DST */
    0x694DA578,   /* 51 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    0x69B0F53D,   /* 52 -- NVRAM_PEN_COLOR */
    0x6A89B90E,   /* 53 -- RESTORE_DEFAULT_AUTOUPDATE_TIME */
    0x6A92C621,   /* 54 -- NVRAM_PEN_SPEED */
    0x6C769ED2,   /* 55 -- NVRAM_SETTING_PEN_SPEED */
    0x6CABCC51,   /* 56 -- NVRAM_SETTING_PEN_WIDTH */
    0x747C6326,   /* 57 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    0x796DC810,   /* 58 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    0x7B8B4124,   /* 59 -- NVRAM_PHNSET_MAIN_MENU_STYLE */
    0x7CEBFAEF,   /* 60 -- NVRAM_AUDPLY_LIST_AUTO_GEN */
    0x7E232E40,   /* 61 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    0x82A4E6B1,   /* 62 -- DATE_FORMAT */
    0x8443B442,   /* 63 -- RESTORE_DEFAULT_DATE_FORMAT */
    0x85365EC5,   /* 64 -- NRRAM_GPS_LOGGING_SWITCH */
    0x8602068E,   /* 65 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    0x8602068F,   /* 66 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    0x86020690,   /* 67 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    0x88D6787D,   /* 68 -- NVRAM_IME_INPUT_PATTERN */
    0x90B5BE24,   /* 69 -- NVRAM_PHB_STARTUP_COPY_SIM */
    0x91CCA231,   /* 70 -- NVRAM_UPDATE_DATETIME_MODE */
    0x9F895786,   /* 71 -- NVRAM_PROFILES_LASTACTIVATED */
    0x9FC8B78B,   /* 72 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    0xA08D6C77,   /* 73 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    0xA1323C32,   /* 74 -- NVRAM_BT_SPEAKER */
    0xA3B72AA6,   /* 75 -- NVRAM_VDOPLY_VOLUMN */
    0xA4F4B75C,   /* 76 -- NVRAM_SETTING_OWNER_NO */
    0xA502111C,   /* 77 -- NVRAM_CALLSET_CTR_MODE */
    0xB084A4EF,   /* 78 -- NVRAM_DOWNLOAD_CITY1 */
    0xB084A4F0,   /* 79 -- NVRAM_DOWNLOAD_CITY2 */
    0xB1A07148,   /* 80 -- NVRAM_DEFAULT_USB_APP */
    0xB3C62531,   /* 81 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    0xB4319F6A,   /* 82 -- NVRAM_IME_SMART_MODE_CONFIG */
    0xB4ADFEE7,   /* 83 -- NVRAM_DT_SEP_FORMAT */
    0xB713C9D4,   /* 84 -- BT_BQB_TEST */
    0xBA41A116,   /* 85 -- NVRAM_SETTING_CONTRAST_LEVEL */
    0xBAB0B4B7,   /* 86 -- NVRAM_IME_VIBRATION_FLAG */
    0xC4713F18,   /* 87 -- NVRAM_BT_MUSIC */
    0xCA6F0937,   /* 88 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    0xCBABBF4B,   /* 89 -- NVRAM_SRV_SNDREC_STORAGE */
    0xD3B20E31,   /* 90 -- NVRAM_VDOPLY_ACTIVE_PROFILE_IDX */
    0xD4572DA9,   /* 91 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    0xD4BAD7B8,   /* 92 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    0xD523D15B,   /* 93 -- NVRAM_NETSET_PREFERRED_MODE */
    0xD598E1F4,   /* 94 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    0xD67F2B01,   /* 95 -- NVRAM_BT_RECEIVE_DRIVE */
    0xDC4F3C00,   /* 96 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    0xDCE10CA4,   /* 97 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    0xDD2BF01B,   /* 98 -- NVRAM_BT_RECEIVE_DRIVE_ASK */
    0xDE69511D,   /* 99 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    0xDEED7E73,   /* 100 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    0xE1A466EE,   /* 101 -- SRV_DT_TIME_ZONE */
    0xE4CB8EFE,   /* 102 -- NVRAM_SETTING_STATUS_DT_TIME */
    0xE639E6DC,   /* 103 -- NVRAM_PROFILES_ACTIVATED */
    0xE8C65B43,   /* 104 -- NVRAM_VDOPLY_PROXY_ON_OFF */
    0xE928235D,   /* 105 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    0xEE1A67D7,   /* 106 -- NVRAM_IME_AUTO_SPACE_FLAG */
    0xEE6763CD,   /* 107 -- NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
    0xF02ECE3A,   /* 108 -- NVRAM_IDLE_SWATCH_INDEX */
    0xF8A67B30,   /* 109 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    0xFA0E117A,   /* 110 -- NVRAM_AUTOUPDATE_DT_STATUS */
    0xFC2179AD,   /* 111 -- NVRAM_IDLE_DIALER_TTS_SETTING */
    0xFCAC03A9,   /* 112 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_SHORT_KEY_DEFAULT[NVRAM_MMI_CACHE_SHORT_KEY_SIZE * NVRAM_MMI_CACHE_SHORT_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x0C2C7116,   /* 0 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
    0x1D0EF6F8,   /* 1 -- NVRAM_VDOPLY_OPTION_BRIGHTNESS */
    0x1D98ABC2,   /* 2 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    0x238E70B2,   /* 3 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    0x2D593480,   /* 4 -- NVRAM_SETTING_WRITING_LANG */
    0x3D11F342,   /* 5 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
    0x3D2C6F38,   /* 6 -- NVRAM_VDOPLY_STORAGE */
    0x421A59BE,   /* 7 -- NVRAM_CALLSET_QUICK_END_TIME */
    0x446216AE,   /* 8 -- NVRAM_PHB_STORAGE_LOCATION */
    0x54329DD6,   /* 9 -- NVRAM_FRN_TIMEZONE */
    0x55C9E89D,   /* 10 -- RESTORE_PREFER_INPUT_METHOD */
    0x61E906E7,   /* 11 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    0x6A59FE18,   /* 12 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    0x6D716BC2,   /* 13 -- NVRAM_VDOPLY_OPTION_REPEAT */
    0x79A7A46A,   /* 14 -- NVRAM_PHB_VCARD_VERSION */
    0x84CB0748,   /* 15 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    0x86773879,   /* 16 -- NVRAM_VDOPLY_SNAPSHOT_SEQ_NO */
    0x890C4A87,   /* 17 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    0x910F4C1A,   /* 18 -- NVRAM_PHB_NAME_LIST_FILTER */
    0xA203F3C0,   /* 19 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
    0xA5052A46,   /* 20 -- NVRAM_CALLSET_CTR_TIME */
    0xA61EEA1C,   /* 21 -- NVRAM_AUDPLY_LAST_PLAYLIST_INDEX */
    0xA9842A5C,   /* 22 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    0xAD3C1B39,   /* 23 -- NVRAM_TIMEZONE */
    0xBAD27847,   /* 24 -- NVRAM_VDOPLY_OPTION_PLAY_MODE */
    0xBC370ACD,   /* 25 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    0xBCD765E1,   /* 26 -- NVRAM_SETTING_WRITING_LANG_SUB */
    0xBE99E6A4,   /* 27 -- NVRAM_IMGVIEW_STORAGE */
    0xC96B627D,   /* 28 -- NVRAM_VDOPLY_STREAM_SEQ_NO */
    0xCF035F69,   /* 29 -- NVRAM_VDOPLY_OPTION_CONTRAST */
    0xD30A9136,   /* 30 -- NVRAM_BT_DIALER_FIRST_BOOT */
    0xD9EACFAC,   /* 31 -- NVRAM_PHB_PBAPC_NAME_ORDER */
    0xDBE1F0F0,   /* 32 -- NVRAM_AUDIO_SPEED_VALUE */
    0xDC2A15F6,   /* 33 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    0xEF592C81,   /* 34 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_DOUBLE_KEY_DEFAULT[NVRAM_MMI_CACHE_DOUBLE_KEY_SIZE * NVRAM_MMI_CACHE_DOUBLE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x029A6DEE,   /* 0 -- NVRAM_AUDIO_DEBUG_INFO1 */
    0x029A6DEF,   /* 1 -- NVRAM_AUDIO_DEBUG_INFO2 */
    0x029A6DF0,   /* 2 -- NVRAM_AUDIO_DEBUG_INFO3 */
    0x029A6DF1,   /* 3 -- NVRAM_AUDIO_DEBUG_INFO4 */
    0x13B9694B,   /* 4 -- NVRAM_RTC_TIME */
    0x29B4FC84,   /* 5 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    0x382F8DD5,   /* 6 -- NVRAM_VDOPLY_PROXY_PORT */
    0x4C5F3D2A,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    0x4C5F3D2B,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    0x4C5F3D2C,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    0x4C5F3D2D,   /* 10 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    0x4C5F3D2E,   /* 11 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    0x4C5F3D2F,   /* 12 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    0x4C5F3D30,   /* 13 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    0x4C5F3D31,   /* 14 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    0x55D698C6,   /* 15 -- NARAM_DISPCHAR_AVATAR_ONOFF */
    0x62F30CB5,   /* 16 -- NVRAM_MRE_SRV_DA_SIM1 */
    0x62F30CB6,   /* 17 -- NVRAM_MRE_SRV_DA_SIM2 */
    0x62F30CB7,   /* 18 -- NVRAM_MRE_SRV_DA_SIM3 */
    0x62F30CB8,   /* 19 -- NVRAM_MRE_SRV_DA_SIM4 */
    0x6CBD743E,   /* 20 -- NVRAM_WLAN_RECONN_PROF_ID */
    0x98AE5398,   /* 21 -- NVRAM_DISPCHAR_AVATAR_WPSS */
    0xA595E229,   /* 22 -- NVRAM_VDOPLY_LOWEST_UDP_PORT */
    0xB68B1B79,   /* 23 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    0xB6B3EF7D,   /* 24 -- NVRAM_VDOPLY_HIGHEST_UDP_PORT */
    0xC384715B,   /* 25 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    0xC384715C,   /* 26 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    0xC384715D,   /* 27 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    0xC384715E,   /* 28 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    0xC384715F,   /* 29 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    0xC3847160,   /* 30 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    0xC3847161,   /* 31 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    0xC3847162,   /* 32 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    0xD017390B,   /* 33 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
    0xD9F529D2,   /* 34 -- NVRAM_MRE_SRV_DA_SIM1_PX */
    0xD9F59E31,   /* 35 -- NVRAM_MRE_SRV_DA_SIM2_PX */
    0xD9F61290,   /* 36 -- NVRAM_MRE_SRV_DA_SIM3_PX */
    0xD9F686EF,   /* 37 -- NVRAM_MRE_SRV_DA_SIM4_PX */
    0xDE4280E0,   /* 38 -- NVRAM_MAINMENU_HIGHLIGHT_INDEX */
};



#ifdef __MTK_INTERNAL__
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif


/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/



#include "mmi_res_range_def.h"
#include "nvram_enums.h"
#include "nvram_interface.h"



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_byte_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_byte to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_byte_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
	 nvram_get_default_value(NVRAM_EF_CACHE_BYTE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BLUETOOTH: 
        buffer[ 95] = def_buf[ 95];     /* 33466: NVRAM_BT_RECEIVE_DRIVE */
        buffer[ 98] = def_buf[ 98];     /* 33467: NVRAM_BT_RECEIVE_DRIVE_ASK */
        buffer[ 11] = def_buf[ 11];     /* 33468: NVRAM_BT_POWER_STATUS */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[ 18] = def_buf[ 18];     /* 35015: NVRAM_IMGVIEW_VIEW_SYTLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        buffer[ 35] = def_buf[ 35];     /* 35358: NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        buffer[ 25] = def_buf[ 25];     /* 35660: NVRAM_AUDPLY_VOLUME */
        buffer[  4] = def_buf[  4];     /* 35661: NVRAM_AUDPLY_PREFER_LIST */
        buffer[ 38] = def_buf[ 38];     /* 35662: NVRAM_AUDPLY_SKIN */
        buffer[ 22] = def_buf[ 22];     /* 35663: NVRAM_AUDPLY_REPEAT */
        buffer[ 19] = def_buf[ 19];     /* 35664: NVRAM_AUDPLY_SHUFFLE */
        buffer[  1] = def_buf[  1];     /* 35665: NVRAM_AUDPLY_BACKGROUND_PLAY */
        buffer[ 37] = def_buf[ 37];     /* 35666: NVRAM_AUDPLY_SPECTRUM_DISPLAY_STYLE */
        buffer[  3] = def_buf[  3];     /* 35667: NVRAM_AUDPLY_LYRICS_DISPLAY */
        buffer[ 20] = def_buf[ 20];     /* 35670: NVRAM_AUDPLY_REMOVE_IN_PROCESS */
        buffer[ 40] = def_buf[ 40];     /* 35671: NVRAM_AUDPLY_SINGLE_VOL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIO_PLAYER_BT: 
        buffer[ 87] = def_buf[ 87];     /* 36266: NVRAM_BT_MUSIC */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 24] = def_buf[ 24];     /* 37531: CURRENT_CITY */
        buffer[ 47] = def_buf[ 47];     /* 37532: FOREIGN_CITY */
        buffer[ 50] = def_buf[ 50];     /* 37533: NVRAM_SETTING_DT_DST */
        buffer[  2] = def_buf[  2];     /* 37535: NVRAM_WC_DST */
        buffer[ 78] = def_buf[ 78];     /* 37537: NVRAM_DOWNLOAD_CITY1 */
        buffer[ 79] = def_buf[ 79];     /* 37538: NVRAM_DOWNLOAD_CITY2 */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 29] = def_buf[ 29];     /* 39900: NVRAM_WALLPAPER_ROTATE_STATUS */
        buffer[ 21] = def_buf[ 21];     /* 39901: NVRAM_PHNSET_LIVE_WALLPAPER */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        buffer[ 76] = def_buf[ 32];     /* 41125: NVRAM_SETTING_OWNER_NO = 41126: RESTORE_DEFAULT_OWNER_NO*/
        buffer[102] = def_buf[102];     /* 41127: NVRAM_SETTING_STATUS_DT_TIME */
        buffer[110] = def_buf[110];     /* 41128: NVRAM_AUTOUPDATE_DT_STATUS */
        buffer[ 70] = def_buf[ 70];     /* 41129: NVRAM_UPDATE_DATETIME_MODE */
        buffer[ 59] = def_buf[ 59];     /* 41131: NVRAM_PHNSET_MAIN_MENU_STYLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BT_DIALER: 
        buffer[ 74] = def_buf[ 74];     /* 44384: NVRAM_BT_SPEAKER */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_VDOPLY: 
        buffer[ 75] = def_buf[ 75];     /* 45968: NVRAM_VDOPLY_VOLUMN */
        buffer[ 90] = def_buf[ 90];     /* 45969: NVRAM_VDOPLY_ACTIVE_PROFILE_IDX */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_MAINMENU: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        buffer[103] = def_buf[103];     /*  7764: NVRAM_PROFILES_ACTIVATED */
        buffer[ 71] = def_buf[ 71];     /*  7765: NVRAM_PROFILES_LASTACTIVATED */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        buffer[  7] = def_buf[  7];     /*  9485: NVRAM_SMS_MISCELL_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IDLE_SWATCH: 
        buffer[108] = def_buf[108];     /* 11577: NVRAM_IDLE_SWATCH_INDEX */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[ 82] = def_buf[ 82];     /* 26102: NVRAM_IME_SMART_MODE_CONFIG */
        buffer[105] = def_buf[105];     /* 26103: NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
        buffer[ 26] = def_buf[ 26];     /* 26104: NVRAM_IME_AUTO_COMPLETION_FLAG */
        buffer[  9] = def_buf[  9];     /* 26105: NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
        buffer[ 88] = def_buf[ 88];     /* 26106: NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
        buffer[106] = def_buf[106];     /* 26107: NVRAM_IME_AUTO_SPACE_FLAG */
        buffer[ 86] = def_buf[ 86];     /* 26108: NVRAM_IME_VIBRATION_FLAG */
        buffer[ 92] = def_buf[ 92];     /* 26109: NVRAM_IME_SOUND_FEEDBACK_FLAG */
        buffer[ 68] = def_buf[ 68];     /* 26110: NVRAM_IME_INPUT_PATTERN */
        buffer[ 55] = def_buf[ 55];     /* 26116: NVRAM_SETTING_PEN_SPEED */
        buffer[ 72] = def_buf[ 72];     /* 26117: NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
        buffer[ 27] = def_buf[ 27];     /* 26118: NVRAM_SETTING_HANDWRITING_ON */
        buffer[ 56] = def_buf[ 56];     /* 26119: NVRAM_SETTING_PEN_WIDTH */
        buffer[ 39] = def_buf[ 39];     /* 26120: NVRAM_SETTING_STROKE_COLOR_INDEX */
        buffer[ 54] = def_buf[ 54];     /* 26121: NVRAM_PEN_SPEED */
        buffer[ 52] = def_buf[ 52];     /* 26122: NVRAM_PEN_COLOR */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        buffer[ 28] = def_buf[ 28];     /* 14510: NVRAM_EF_FMGR_SORT_OPTION_LID */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MDI: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 85] = def_buf[ 85];     /* 26225: NVRAM_SETTING_CONTRAST_LEVEL */
        buffer[ 34] = def_buf[ 34];     /* 26230: NVRAM_BYTE_LED_SETTING */
        buffer[ 73] = def_buf[ 73];     /* 26231: NVRAM_BYTE_BL_SETTING_LEVEL */
        buffer[  0] = def_buf[  0];     /* 26233: NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        buffer[  6] = def_buf[  6];     /* 26256: NVRAM_SETTING_PICTURE_QUALITY */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_BTCM: 
        buffer[ 84] = def_buf[ 84];     /* 18166: BT_BQB_TEST */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        buffer[ 93] = def_buf[ 93];     /* 26287: NVRAM_NETSET_PREFERRED_MODE */
        buffer[ 57] = def_buf[ 57];     /* 26288: NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
        buffer[ 13] = def_buf[ 13];     /* 26289: NVRAM_NETSET_3G_CAPACITY_SIM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 77] = def_buf[ 77];     /*  9588: NVRAM_CALLSET_CTR_MODE */
        buffer[112] = def_buf[112];     /*  9589: NVRAM_CALLSET_ANSWER_MODE */
        buffer[ 44] = def_buf[ 44];     /*  9590: NVRAM_CALLSET_CALL_TIME_DISPLAY */
        buffer[ 41] = def_buf[ 41];     /*  9591: NVRAM_CALLSET_REDIAL */
        buffer[ 33] = def_buf[ 33];     /*  9592: NVRAM_CALLSET_QUICK_END_FLAG */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        buffer[ 91] = def_buf[ 91];     /* 27088: NVRAM_DUALMODE_MODE_SWITCH_TYPE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        buffer[ 48] = def_buf[ 48];     /* 27130: TIME_FORMAT */
        buffer[ 62] = def_buf[ 62];     /* 27131: DATE_FORMAT */
        buffer[ 83] = def_buf[ 83];     /* 27134: NVRAM_DT_SEP_FORMAT */
        buffer[  5] = def_buf[  5];     /* 27135: NVRAM_SETTING_LANG */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_DATETIME_SETTING: 
        buffer[  8] = def_buf[  8];     /* 27234: GPS_TIME_SYNC_MODE */
        buffer[101] = def_buf[101];     /* 27235: SRV_DT_TIME_ZONE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WLAN: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        buffer[111] = def_buf[111];     /* 28322: NVRAM_IDLE_DIALER_TTS_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        buffer[ 99] = def_buf[ 99];     /* 28291: NVRAM_SETTING_AUTOKEYPADLOCK */
        buffer[ 23] = def_buf[ 23];     /* 28292: NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        buffer[ 81] = def_buf[ 81];     /* 30139: NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        buffer[ 89] = def_buf[ 89];     /* 30213: NVRAM_SRV_SNDREC_STORAGE */
        buffer[ 46] = def_buf[ 46];     /* 30214: NVRAM_SRV_SNDREC_QUALITY */
        buffer[ 96] = def_buf[ 96];     /* 30215: NVRAM_AUTO_VM_SETTING_AUTO_VM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 36] = def_buf[ 36];     /* 32042: NVRAM_PHB_SPEAK_NAME_ON_OFF */
        buffer[ 43] = def_buf[ 43];     /* 32047: NVRAM_PHB_NAME_DISPLAY_TYPE */
        buffer[ 12] = def_buf[ 12];     /* 32051: NVRAM_PHB_SAVE_CONTACT_NOTIFY */
        buffer[ 58] = def_buf[ 58];     /* 32053: NVRAM_IDLE_DIALER_SEARCH_SETTING */
        buffer[ 31] = def_buf[ 31];     /* 32054: NVRAM_SETTING_SPEED_DIAL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        buffer[107] = def_buf[107];     /* 32228: NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_short_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_short to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_short_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
	 nvram_get_default_value(NVRAM_EF_CACHE_SHORT_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BLUETOOTH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        buffer[ 60] = def_buf[ 60];     /* 33918: NVRAM_BT_DIALER_FIRST_BOOT */
        buffer[ 61] = def_buf[ 61];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[ 54] = def_buf[ 54];     /* 35016: NVRAM_IMGVIEW_STORAGE */
        buffer[ 55] = def_buf[ 55];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        buffer[ 64] = def_buf[ 64];     /* 35669: NVRAM_AUDIO_SPEED_VALUE */
        buffer[ 65] = def_buf[ 65];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIO_PLAYER_BT: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 46] = def_buf[ 46];     /* 37534: NVRAM_TIMEZONE */
        buffer[ 47] = def_buf[ 47];
        buffer[ 18] = def_buf[ 18];     /* 37536: NVRAM_FRN_TIMEZONE */
        buffer[ 19] = def_buf[ 19];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 66] = def_buf[ 66];     /* 39902: NVRAM_FUNANDGAMES_SETWALLPAPER */
        buffer[ 67] = def_buf[ 67];
        buffer[ 68] = def_buf[ 22];     /* 39904: NVRAM_SETWALLPAPER_SUB = 39905: RESTORE_DEFAULT_SETWALLPAPER_SUB*/
        buffer[ 69] = def_buf[ 23];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        buffer[ 10] = def_buf[ 50];     /* 40100: NVRAM_CURRENT_POWER_ON_DISPLAY = 40098: NVRAM_RESTORE_POWER_ON_DISPLAY*/
        buffer[ 11] = def_buf[ 51];
        buffer[  6] = def_buf[ 34];     /* 40101: NVRAM_CURRENT_POWER_OFF_DISPLAY = 40099: NVRAM_RESTORE_POWER_OFF_DISPLAY*/
        buffer[  7] = def_buf[ 35];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BT_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_VDOPLY: 
        buffer[ 12] = def_buf[ 12];     /* 45976: NVRAM_VDOPLY_STORAGE */
        buffer[ 13] = def_buf[ 13];
        buffer[  2] = def_buf[  2];     /* 45977: NVRAM_VDOPLY_OPTION_BRIGHTNESS */
        buffer[  3] = def_buf[  3];
        buffer[ 58] = def_buf[ 58];     /* 45978: NVRAM_VDOPLY_OPTION_CONTRAST */
        buffer[ 59] = def_buf[ 59];
        buffer[ 26] = def_buf[ 26];     /* 45979: NVRAM_VDOPLY_OPTION_REPEAT */
        buffer[ 27] = def_buf[ 27];
        buffer[ 48] = def_buf[ 48];     /* 45980: NVRAM_VDOPLY_OPTION_PLAY_MODE */
        buffer[ 49] = def_buf[ 49];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_MAINMENU: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IDLE_SWATCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[  0] = def_buf[ 20];     /* 26111: NVRAM_SETTING_PREFER_INPUT_METHOD = 26112: RESTORE_PREFER_INPUT_METHOD*/
        buffer[  1] = def_buf[ 21];
        buffer[  8] = def_buf[  8];     /* 26113: NVRAM_SETTING_WRITING_LANG */
        buffer[  9] = def_buf[  9];
        buffer[ 52] = def_buf[ 52];     /* 26114: NVRAM_SETTING_WRITING_LANG_SUB */
        buffer[ 53] = def_buf[ 53];
        buffer[ 30] = def_buf[ 30];     /* 26115: NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
        buffer[ 31] = def_buf[ 31];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MDI: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 24] = def_buf[ 24];     /* 26232: NVRAM_BYTE_BL_SETTING_HFTIME */
        buffer[ 25] = def_buf[ 25];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_BTCM: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 14] = def_buf[ 14];     /*  9594: NVRAM_CALLSET_QUICK_END_TIME */
        buffer[ 15] = def_buf[ 15];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_DATETIME_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WLAN: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 16] = def_buf[ 16];     /* 32048: NVRAM_PHB_STORAGE_LOCATION */
        buffer[ 17] = def_buf[ 17];
        buffer[ 36] = def_buf[ 36];     /* 32049: NVRAM_PHB_NAME_LIST_FILTER */
        buffer[ 37] = def_buf[ 37];
        buffer[ 28] = def_buf[ 28];     /* 32050: NVRAM_PHB_VCARD_VERSION */
        buffer[ 29] = def_buf[ 29];
        buffer[ 62] = def_buf[ 62];     /* 32055: NVRAM_PHB_PBAPC_NAME_ORDER */
        buffer[ 63] = def_buf[ 63];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_double_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_double to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_double_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
	 nvram_get_default_value(NVRAM_EF_CACHE_DOUBLE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BLUETOOTH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIO_PLAYER_BT: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[168] = def_buf[168];     /* 39896: NVRAM_DISPCHAR_AVATAR_WPSS */
        buffer[169] = def_buf[169];
        buffer[170] = def_buf[170];
        buffer[171] = def_buf[171];
        buffer[172] = def_buf[172];
        buffer[173] = def_buf[173];
        buffer[174] = def_buf[174];
        buffer[175] = def_buf[175];
        buffer[120] = def_buf[120];     /* 39897: NARAM_DISPCHAR_AVATAR_ONOFF */
        buffer[121] = def_buf[121];
        buffer[122] = def_buf[122];
        buffer[123] = def_buf[123];
        buffer[124] = def_buf[124];
        buffer[125] = def_buf[125];
        buffer[126] = def_buf[126];
        buffer[127] = def_buf[127];
        buffer[264] = def_buf[264];     /* 39898: NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
        buffer[265] = def_buf[265];
        buffer[266] = def_buf[266];
        buffer[267] = def_buf[267];
        buffer[268] = def_buf[268];
        buffer[269] = def_buf[269];
        buffer[270] = def_buf[270];
        buffer[271] = def_buf[271];
        buffer[ 40] = def_buf[ 40];     /* 39899: NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
        buffer[ 41] = def_buf[ 41];
        buffer[ 42] = def_buf[ 42];
        buffer[ 43] = def_buf[ 43];
        buffer[ 44] = def_buf[ 44];
        buffer[ 45] = def_buf[ 45];
        buffer[ 46] = def_buf[ 46];
        buffer[ 47] = def_buf[ 47];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        buffer[ 32] = def_buf[ 32];     /* 41130: NVRAM_RTC_TIME */
        buffer[ 33] = def_buf[ 33];
        buffer[ 34] = def_buf[ 34];
        buffer[ 35] = def_buf[ 35];
        buffer[ 36] = def_buf[ 36];
        buffer[ 37] = def_buf[ 37];
        buffer[ 38] = def_buf[ 38];
        buffer[ 39] = def_buf[ 39];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BT_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_VDOPLY: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_MAINMENU: 
        buffer[304] = def_buf[304];     /* 47530: NVRAM_MAINMENU_HIGHLIGHT_INDEX */
        buffer[305] = def_buf[305];
        buffer[306] = def_buf[306];
        buffer[307] = def_buf[307];
        buffer[308] = def_buf[308];
        buffer[309] = def_buf[309];
        buffer[310] = def_buf[310];
        buffer[311] = def_buf[311];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IDLE_SWATCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MDI: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_BTCM: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        buffer[200] = def_buf[ 56];     /* 27107: NVRAM_PEN_CALIBRATION_VALUE1 = 27099: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1*/
        buffer[201] = def_buf[ 57];
        buffer[202] = def_buf[ 58];
        buffer[203] = def_buf[ 59];
        buffer[204] = def_buf[ 60];
        buffer[205] = def_buf[ 61];
        buffer[206] = def_buf[ 62];
        buffer[207] = def_buf[ 63];
        buffer[208] = def_buf[ 64];     /* 27108: NVRAM_PEN_CALIBRATION_VALUE2 = 27100: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2*/
        buffer[209] = def_buf[ 65];
        buffer[210] = def_buf[ 66];
        buffer[211] = def_buf[ 67];
        buffer[212] = def_buf[ 68];
        buffer[213] = def_buf[ 69];
        buffer[214] = def_buf[ 70];
        buffer[215] = def_buf[ 71];
        buffer[216] = def_buf[ 72];     /* 27109: NVRAM_PEN_CALIBRATION_VALUE3 = 27101: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3*/
        buffer[217] = def_buf[ 73];
        buffer[218] = def_buf[ 74];
        buffer[219] = def_buf[ 75];
        buffer[220] = def_buf[ 76];
        buffer[221] = def_buf[ 77];
        buffer[222] = def_buf[ 78];
        buffer[223] = def_buf[ 79];
        buffer[224] = def_buf[ 80];     /* 27110: NVRAM_PEN_CALIBRATION_VALUE4 = 27102: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4*/
        buffer[225] = def_buf[ 81];
        buffer[226] = def_buf[ 82];
        buffer[227] = def_buf[ 83];
        buffer[228] = def_buf[ 84];
        buffer[229] = def_buf[ 85];
        buffer[230] = def_buf[ 86];
        buffer[231] = def_buf[ 87];
        buffer[232] = def_buf[ 88];     /* 27111: NVRAM_PEN_CALIBRATION_VALUE5 = 27103: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5*/
        buffer[233] = def_buf[ 89];
        buffer[234] = def_buf[ 90];
        buffer[235] = def_buf[ 91];
        buffer[236] = def_buf[ 92];
        buffer[237] = def_buf[ 93];
        buffer[238] = def_buf[ 94];
        buffer[239] = def_buf[ 95];
        buffer[240] = def_buf[ 96];     /* 27112: NVRAM_PEN_CALIBRATION_VALUE6 = 27104: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6*/
        buffer[241] = def_buf[ 97];
        buffer[242] = def_buf[ 98];
        buffer[243] = def_buf[ 99];
        buffer[244] = def_buf[100];
        buffer[245] = def_buf[101];
        buffer[246] = def_buf[102];
        buffer[247] = def_buf[103];
        buffer[248] = def_buf[104];     /* 27113: NVRAM_PEN_CALIBRATION_VALUE7 = 27105: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7*/
        buffer[249] = def_buf[105];
        buffer[250] = def_buf[106];
        buffer[251] = def_buf[107];
        buffer[252] = def_buf[108];
        buffer[253] = def_buf[109];
        buffer[254] = def_buf[110];
        buffer[255] = def_buf[111];
        buffer[256] = def_buf[112];     /* 27114: NVRAM_PEN_CALIBRATION_VALUE8 = 27106: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8*/
        buffer[257] = def_buf[113];
        buffer[258] = def_buf[114];
        buffer[259] = def_buf[115];
        buffer[260] = def_buf[116];
        buffer[261] = def_buf[117];
        buffer[262] = def_buf[118];
        buffer[263] = def_buf[119];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_DATETIME_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WLAN: 
        buffer[160] = def_buf[160];     /*  9372: NVRAM_WLAN_RECONN_PROF_ID */
        buffer[161] = def_buf[161];
        buffer[162] = def_buf[162];
        buffer[163] = def_buf[163];
        buffer[164] = def_buf[164];
        buffer[165] = def_buf[165];
        buffer[166] = def_buf[166];
        buffer[167] = def_buf[167];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}


